local PLUGIN = PLUGIN or {}

PLUGIN.name = ""
PLUGIN.author = ""
PLUGIN.description = ""

-- Ruch / poruszanie się
Schema.voices.Add("Combine", "PRZEMIESZCZAM_SIE", "Poruszam się.", "HLAComVoice/grunt/advancing_on_target_01.wav")
Schema.voices.Add("Combine", "PRZEMIESZCZAM_SIE2", "Poruszam się teraz.", "HLAComVoice/grunt/advancing_on_target_02.wav")
Schema.voices.Add("Combine", "PRZEMIESZCZAM_SIE_TERAZ", "Poruszam się teraz.", "HLAComVoice/grunt/advancing_on_target_02.wav")
Schema.voices.Add("Combine", "PRZEMIESZCZAM_SIE3", "Tłumię.", "HLAComVoice/grunt/advancing_on_target_03.wav")
Schema.voices.Add("Combine", "TLUMIE1", "Tłumię.", "HLAComVoice/grunt/advancing_on_target_03.wav")
Schema.voices.Add("Combine", "ZBLIZAM_SIE_DO_CELU", "Zbliżam się do celu.", "HLAComVoice/grunt/advancing_on_target_04.wav")
Schema.voices.Add("Combine", "TLUM", "Tłum.", "HLAComVoice/grunt/advancing_on_target_05.wav")
Schema.voices.Add("Combine", "ZBLIZAM_SIE_DO_ZARAZONEGO", "Zbliżam się do zainfekowanego.", "HLAComVoice/grunt/advancing_on_target_06.wav")
Schema.voices.Add("Combine", "OSTROZNIE_NAPRZOD", "Ostrożnie naprzód.", "HLAComVoice/grunt/advancing_on_target_07.wav")
Schema.voices.Add("Combine", "POSUWAM_SIE2", "Posuwam się naprzód.", "HLAComVoice/grunt/advancing_on_target_08.wav")
Schema.voices.Add("Combine", "POSUWAM_SIE_NAPRZOD", "Posuwam się naprzód.", "HLAComVoice/grunt/advancing_on_target_08.wav")
Schema.voices.Add("Combine", "PRZEMIESZCZAM_SIE_DO_SKAZENIA", "Przemieszczam się do skażenia.", "HLAComVoice/grunt/advancing_on_target_10.wav")
Schema.voices.Add("Combine", "POSUWAMY_SIE2", "Posuwamy się!", "HLAComVoice/grunt/advancing_on_target_11.wav")
Schema.voices.Add("Combine", "POSUWAMY_SIE", "Posuwamy się!", "HLAComVoice/grunt/advancing_on_target_11.wav")
Schema.voices.Add("Combine", "ZBLIZAM_SIE_DO_ZAINFEKOWANEGO", "Zbliżam się do zainfekowanego.", "HLAComVoice/grunt/advancing_on_target_13.wav")
Schema.voices.Add("Combine", "POSUWAM_SIE", "Posuwam się.", "HLAComVoice/grunt/advancing_on_target_14.wav")
Schema.voices.Add("Combine", "POSUWAM_SIE3", "Posuwam się do sektora.", "HLAComVoice/grunt/advancing_on_target_16.wav")
Schema.voices.Add("Combine", "POSUWAM_SIE_DO_SEKTORA", "Posuwam się do sektora.", "HLAComVoice/grunt/advancing_on_target_16.wav")
Schema.voices.Add("Combine", "ZBLIZAM_SIE_DO_ZARAZONEGO2", "Zbliżam się do zainfekowanego.", "HLAComVoice/grunt/advancing_on_target_17.wav")

-- Ogłaszanie ataku
Schema.voices.Add("Combine", "ATAKUJE", "Atakuję!", "HLAComVoice/grunt/announceattack_01.wav")
Schema.voices.Add("Combine", "SKUPIC_SIE", "Skupić się!", "HLAComVoice/grunt/announceattack_01.wav")
Schema.voices.Add("Combine", "ATAKUJE2", "Zbliżam się!", "HLAComVoice/grunt/announceattack_02.wav")
Schema.voices.Add("Combine", "ZBLIZAM_SIE", "Skracam dystans!", "HLAComVoice/grunt/announceattack_02.wav")
Schema.voices.Add("Combine", "ATAKUJE3", "Cel jest atakowany.", "HLAComVoice/grunt/announceattack_03.wav")
Schema.voices.Add("Combine", "ATAKUJE4", "Ścigam.", "HLAComVoice/grunt/announceattack_04.wav")
Schema.voices.Add("Combine", "SCIGAM", "Ścigam.", "HLAComVoice/grunt/announceattack_04.wav")
Schema.voices.Add("Combine", "ATAKUJE5", "Odpowiadam uprzedzającym ogniem.", "HLAComVoice/grunt/announceattack_05.wav")
Schema.voices.Add("Combine", "ATAKUJE6", "Pod ostrzałem.", "HLAComVoice/grunt/announceattack_06.wav")
Schema.voices.Add("Combine", "POD_OGNIEM", "Pod ostrzałem.", "HLAComVoice/grunt/announceattack_06.wav")
Schema.voices.Add("Combine", "ATAKUJE7", "Atakuję uprzedzająco.", "HLAComVoice/grunt/announceattack_07.wav")
Schema.voices.Add("Combine", "ATAKUJE8", "Wykorzystuję przewagę.", "HLAComVoice/grunt/announceattack_08.wav")
Schema.voices.Add("Combine", "ATAKUJE9", "Cel namierzony, broń ustawiona.", "HLAComVoice/grunt/announceattack_09.wav")
Schema.voices.Add("Combine", "OTWORZ_OGIEN", "Otworzyć ogień.", "HLAComVoice/grunt/announceattack_11.wav")

-- Ogłaszanie ataku na Gracza/Alyx
Schema.voices.Add("Combine", "CEL_NUMER_JEDEN", "Cel numer jeden w polu widzenia.", "HLAComVoice/grunt/announceattack_alyx_01.wav")
Schema.voices.Add("Combine", "ZATRZYMAJ_SIE_TERAZ", "Zatrzymać się, teraz!", "HLAComVoice/grunt/announceattack_alyx_02.wav")
Schema.voices.Add("Combine", "CEL_NUMER_JEDEN2", "Zgarnęliśmy niezłą zdobycz.", "HLAComVoice/grunt/announceattack_alyx_03.wav")
Schema.voices.Add("Combine", "CEL_NUMER_JEDEN_RANNY", "Cel numer jeden jest ranny.", "HLAComVoice/grunt/announceattack_alyx_04.wav")
Schema.voices.Add("Combine", "TRZYMAM_JA", "Trzymam ją!", "HLAComVoice/grunt/announceattack_alyx_05.wav")
Schema.voices.Add("Combine", "TO_ONA", "To ona!", "HLAComVoice/grunt/announceattack_alyx_11.wav")

-- Ogłaszanie ataku na ukrycie
Schema.voices.Add("Combine", "ROZBIJAM_UKRYCIE", "Rozbijam maskowanie.", "HLAComVoice/grunt/announceattack_cover_01.wav")
Schema.voices.Add("Combine", "ROZKRYWAM_MASKOWANIE", "Rozkrywam maskowanie.", "HLAComVoice/grunt/announceattack_cover_01.wav")
Schema.voices.Add("Combine", "ROZBIJAM_UKRYCIE2", "Zmiana celu, kod obławy.", "HLAComVoice/grunt/announceattack_cover_02.wav")
Schema.voices.Add("Combine", "ROZBIJAM_UKRYCIE3", "Oznacz cel jako cień.", "HLAComVoice/grunt/announceattack_cover_03.wav")
Schema.voices.Add("Combine", "ROZKRYWAM_WROGA_ZA_3", "Wykrywamy wroga za 3…", "HLAComVoice/grunt/announceattack_cover_04.wav")
Schema.voices.Add("Combine", "ROZBIJAM_UKRYCIE4", "Cel opancerzony, korygujemy.", "HLAComVoice/grunt/announceattack_cover_05.wav")
Schema.voices.Add("Combine", "ROZBIJAM_UKRYCIE5", "Otwieram ogień na ukrycie.", "HLAComVoice/grunt/announceattack_cover_08.wav")
Schema.voices.Add("Combine", "ROZBIJAM_UKRYCIE6", "Kod obławy!", "HLAComVoice/grunt/announceattack_cover_10.wav")

-- Ogłaszanie ataku granatem
Schema.voices.Add("Combine", "RZUCAM_GRANAT", "Granat!", "HLAComVoice/grunt/announceattack_grenade_01.wav")
Schema.voices.Add("Combine", "RZUCAM_GRANAT2", "Rzucam granat!", "HLAComVoice/grunt/announceattack_grenade_02.wav")
Schema.voices.Add("Combine", "RZUCAM_GRANAT3", "...zawleczka wyrwana!", "HLAComVoice/grunt/announceattack_grenade_03.wav")
Schema.voices.Add("Combine", "RZUCAM_GRANAT4", "Granat, granat!", "HLAComVoice/grunt/announceattack_grenade_04.wav")
Schema.voices.Add("Combine", "GRANAT_GRANAT", "Granat, granat!", "HLAComVoice/grunt/announceattack_grenade_04.wav")
Schema.voices.Add("Combine", "RZUCAM_GRANAT5", "Granat, szukam osłony!", "HLAComVoice/grunt/announceattack_grenade_05.wav")
Schema.voices.Add("Combine", "DO_OSLONY", "Do osłony!", "HLAComVoice/grunt/announceattack_grenade_05.wav")
Schema.voices.Add("Combine", "GRANAT_NA_3", "Granat za 3…", "HLAComVoice/grunt/announceattack_grenade_06.wav")
Schema.voices.Add("Combine", "RZUCAM_GRANAT6", "...wyrwane!", "HLAComVoice/grunt/announceattack_grenade_07.wav")
Schema.voices.Add("Combine", "RZUCAM_GRANAT7", "Rzucam granat!", "HLAComVoice/grunt/announceattack_grenade_08.wav")
Schema.voices.Add("Combine", "RZUCAM_GRANAT8", "Wszyscy do tyłu!", "HLAComVoice/grunt/announceattack_grenade_09.wav")
Schema.voices.Add("Combine", "RZUCAM_GRANAT9", "Łap granat!", "HLAComVoice/grunt/announceattack_grenade_10.wav")

-- Ogłaszanie wroga Antlion (Muравьиный лев)
Schema.voices.Add("Combine", "ANTLION2", "ANTLION!", "HLAComVoice/grunt/announceenemy_antlion_01.wav")
Schema.voices.Add("Combine", "ANTLION3", "Cel: antlion!", "HLAComVoice/grunt/announceenemy_antlion_02.wav")
Schema.voices.Add("Combine", "ANTLION4", "Kontakt, antlion!", "HLAComVoice/grunt/announceenemy_antlion_03.wav")
Schema.voices.Add("Combine", "ANTLION5", "antliony nacierają!", "HLAComVoice/grunt/announceenemy_antlion_04.wav")
Schema.voices.Add("Combine", "ANTLION6", "Kontakt, antlion!", "HLAComVoice/grunt/announceenemy_antlion_05.wav")
Schema.voices.Add("Combine", "ANTLION7", "Kontakt wzrokowy, antlion!", "HLAComVoice/grunt/announceenemy_antlion_06.wav")
Schema.voices.Add("Combine", "ANTLION8", "antlion jest tutaj!", "HLAComVoice/grunt/announceenemy_antlion_10.wav")

-- Ogłaszanie wroga Headcrab
Schema.voices.Add("Combine", "HEADCRAB2", "Pasożyty!", "HLAComVoice/grunt/announceenemy_headcrabs_01.wav")
Schema.voices.Add("Combine", "HEADCRAB3", "Pasożyty w sektorze.", "HLAComVoice/grunt/announceenemy_headcrabs_02.wav")
Schema.voices.Add("Combine", "3_HEADCRABY", "Cholera, kontakt z trzema pasożytami.", "HLAComVoice/grunt/announceenemy_headcrabs_03.wav")
Schema.voices.Add("Combine", "HEADCRAB4", "Kontakt, pasożyty.", "HLAComVoice/grunt/announceenemy_headcrabs_05.wav")
Schema.voices.Add("Combine", "NIE_CIERPIE_TYCH_RZECZY", "Nienawidzę tych rzeczy.", "HLAComVoice/grunt/announceenemy_headcrabs_06.wav")
Schema.voices.Add("Combine", "HEADCRAB5", "Mamy tu pasożyty!", "HLAComVoice/grunt/announceenemy_headcrabs_07.wav")
Schema.voices.Add("Combine", "HEADCRAB6", "Pasożyty tutaj!", "HLAComVoice/grunt/announceenemy_headcrabs_09.wav")
Schema.voices.Add("Combine", "HEADCRAB7", "Potwierdzone pasożytnicze skażenie.", "HLAComVoice/grunt/announceenemy_headcrabs_10.wav")

-- Ogłaszanie wroga Zombie
Schema.voices.Add("Combine", "ZOMBIE2", "Nekrotyki!", "HLAComVoice/grunt/announceenemy_zombie_01.wav")
Schema.voices.Add("Combine", "ZOMBIE3", "Nekrotyki nadchodzą!", "HLAComVoice/grunt/announceenemy_zombie_02.wav")
Schema.voices.Add("Combine", "ZAGROZENIE_ZARAZENIEM", "Zagrożenie infekcją!", "HLAComVoice/grunt/announceenemy_zombie_03.wav")
Schema.voices.Add("Combine", "ZOMBIE4", "Kontakt, nekrotyki!", "HLAComVoice/grunt/announceenemy_zombie_05.wav")
Schema.voices.Add("Combine", "ZOMBIE5", "Widzę nekrotyki!", "HLAComVoice/grunt/announceenemy_zombie_06.wav")
Schema.voices.Add("Combine", "ZOMBIE6", "Mamy nekrotyki!", "HLAComVoice/grunt/announceenemy_zombie_07.wav")
Schema.voices.Add("Combine", "ZOMBIE7", "Nekrotyki są aktywne.", "HLAComVoice/grunt/announceenemy_zombie_08.wav")
Schema.voices.Add("Combine", "ZOMBIE8", "Kontakt z nekrotykami!", "HLAComVoice/grunt/announceenemy_zombie_09.wav")
Schema.voices.Add("Combine", "ZOMBIE9", "Tutaj są nekrotyki.", "HLAComVoice/grunt/announceenemy_zombie_10.wav")

-- Ogłaszanie zabójstwa
Schema.voices.Add("Combine", "ZABITY", "Wróg zabity.", "HLAComVoice/grunt/announcekill_01.wav")
Schema.voices.Add("Combine", "ZABITY2", "Cel zabity.", "HLAComVoice/grunt/announcekill_02.wav")
Schema.voices.Add("Combine", "ZABITY3", "Zabicie potwierdzone.", "HLAComVoice/grunt/announcekill_03.wav")
Schema.voices.Add("Combine", "W_GLOWE", "W głowę.", "HLAComVoice/grunt/announcekill_04.wav")
Schema.voices.Add("Combine", "ZABITY5", "Jeszcze jeden zabity.", "HLAComVoice/grunt/announcekill_05.wav")
Schema.voices.Add("Combine", "ZABITY6", "Wykończyłem.", "HLAComVoice/grunt/announcekill_06.wav")
Schema.voices.Add("Combine", "WYKONCZONY", "Wykończyłem.", "HLAComVoice/grunt/announcekill_06.wav")
Schema.voices.Add("Combine", "ZABITY7", "Martwy.", "HLAComVoice/grunt/announcekill_07.wav")
Schema.voices.Add("Combine", "MARTWY", "Martwy.", "HLAComVoice/grunt/announcekill_07.wav")
Schema.voices.Add("Combine", "ZABITY8", "W głowę!", "HLAComVoice/grunt/announcekill_08.wav")
Schema.voices.Add("Combine", "ZABITY9", "Cel zabity!", "HLAComVoice/grunt/announcekill_09.wav")
Schema.voices.Add("Combine", "ONI_MARTWI", "Oni nie żyją.", "HLAComVoice/grunt/announcekill_11.wav")
Schema.voices.Add("Combine", "ZABITY4", "Wróg zneutralizowany.", "HLAComVoice/grunt/announcekill_13.wav")
Schema.voices.Add("Combine", "SKONCZONE", "Skończone.", "HLAComVoice/grunt/announcekill_14.wav")
Schema.voices.Add("Combine", "WROG_ZGON", "Wróg nie żyje.", "HLAComVoice/grunt/announcekill_15.wav")

-- Zabicie - Antlion
Schema.voices.Add("Combine", "MROWKOLW_MARTWY", "Mrówkolwy zabite.", "HLAComVoice/grunt/announcekill_antlion_01.wav")
Schema.voices.Add("Combine", "MROWKOLW_MARTWY2", "Czysto.", "HLAComVoice/grunt/announcekill_antlion_02.wav")
Schema.voices.Add("Combine", "CZYSTO", "Czysto.", "HLAComVoice/grunt/announcekill_antlion_02.wav")
Schema.voices.Add("Combine", "MROWKOLW_MARTWY3", "Cel wysterylizowany.", "HLAComVoice/grunt/announcekill_antlion_03.wav")
Schema.voices.Add("Combine", "MROWKOLW_MARTWY4", "Zmazany.", "HLAComVoice/grunt/announcekill_antlion_04.wav")
Schema.voices.Add("Combine", "ZMAZANY", "Zmazany.", "HLAComVoice/grunt/announcekill_antlion_04.wav")
Schema.voices.Add("Combine", "MROWKOLW_MARTWY5", "Pasożyt powstrzymany!", "HLAComVoice/grunt/announcekill_antlion_05.wav")

-- Zabicie - Headcrab
Schema.voices.Add("Combine", "HEADCRAB_MARTWY", "Czysto.", "HLAComVoice/grunt/announcekill_headcrab_01.wav")
Schema.voices.Add("Combine", "SEKTOR_WYCZYSZCZONY", "Sektor oczyszczony, poruszam się dalej.", "HLAComVoice/grunt/announcekill_headcrab_02.wav")
Schema.voices.Add("Combine", "HEADCRAB_MARTWY2", "Ustrzeliłem jednego.", "HLAComVoice/grunt/announcekill_headcrab_03.wav")
Schema.voices.Add("Combine", "HEADCRAB_MARTWY3", "Skażenie powstrzymane.", "HLAComVoice/grunt/announcekill_headcrab_04.wav")
Schema.voices.Add("Combine", "HEADCRAB_MARTWY4", "Oczyszczone.", "HLAComVoice/grunt/announcekill_headcrab_05.wav")
Schema.voices.Add("Combine", "GLUPSTWO", "Gadostwo.", "HLAComVoice/grunt/announcekill_headcrab_06.wav")
Schema.voices.Add("Combine", "WYBIJ_PRZELAMANY", "Przełom zlikwidowany.", "HLAComVoice/grunt/announcekill_headcrab_07.wav")
Schema.voices.Add("Combine", "PRZELAMANY_WSTRZYMANO", "Przełom wstrzymany.", "HLAComVoice/grunt/announcekill_headcrab_08.wav")
Schema.voices.Add("Combine", "HEADCRAB_MARTWY6", "Pasożyt unieszkodliwiony.", "HLAComVoice/grunt/announcekill_headcrab_09.wav")

-- Zabicie - Gracz/Alyx
Schema.voices.Add("Combine", "VIP_MARTWY", "Priorytetowy cel powstrzymany.", "HLAComVoice/grunt/announcekill_player_01.wav")
Schema.voices.Add("Combine", "VIP_MARTWY2", "Cel numer jeden uciszony.", "HLAComVoice/grunt/announcekill_player_02.wav")
Schema.voices.Add("Combine", "ONA_UCISZONA", "Ona jest uciszona.", "HLAComVoice/grunt/announcekill_player_03.wav")
Schema.voices.Add("Combine", "MARTWY2", "Martwy.", "HLAComVoice/grunt/announcekill_player_07.wav")
Schema.voices.Add("Combine", "VIP_UBITY", "I oto główny wróg został wyeliminowany.", "HLAComVoice/grunt/announcekill_player_08.wav")

-- Zabicie - Zombie
Schema.voices.Add("Combine", "ZOMBIE_MARTWY", "Nekro powstrzymany.", "HLAComVoice/grunt/announcekill_zombie_01.wav")
Schema.voices.Add("Combine", "ZOMBIE_MARTWY2", "Nekrotyk powstrzymany.", "HLAComVoice/grunt/announcekill_zombie_02.wav")
Schema.voices.Add("Combine", "ZOSTAN_MARTWY", "Zostań martwy!", "HLAComVoice/grunt/announcekill_zombie_03.wav")
Schema.voices.Add("Combine", "ZOMBIE_MARTWY4", "Zainfekowany zniszczony.", "HLAComVoice/grunt/announcekill_zombie_04.wav")
Schema.voices.Add("Combine", "ZOMBIE_MARTWY5", "Wracaj spać.", "HLAComVoice/grunt/announcekill_zombie_05.wav")
Schema.voices.Add("Combine", "WRACAJ_SPAC", "Wracaj spać.", "HLAComVoice/grunt/announcekill_zombie_05.wav")
Schema.voices.Add("Combine", "ZOMBIE_MARTWY6", "To coś nie żyje.", "HLAComVoice/grunt/announcekill_zombie_06.wav")
Schema.voices.Add("Combine", "TO_COS_MARTWE", "To coś nie żyje.", "HLAComVoice/grunt/announcekill_zombie_06.wav")
Schema.voices.Add("Combine", "ZOMBIE_MARTWY7", "Czyszczenie zakończone sukcesem.", "HLAComVoice/grunt/announcekill_zombie_07.wav")

-- Odgłosy oddychania
Schema.voices.Add("Combine", "ODDYCHA", "*Ciężki oddech*", "HLAComVoice/grunt/breathing_01.wav")
Schema.voices.Add("Combine", "ODDYCHA2", "*Ciężki oddech*", "HLAComVoice/grunt/breathing_02.wav")
Schema.voices.Add("Combine", "ODDYCHA3", "*Ciężki oddech*", "HLAComVoice/grunt/breathing_03.wav")
Schema.voices.Add("Combine", "ODDYCHA4", "*Ciężki oddech*", "HLAComVoice/grunt/breathing_04.wav")
Schema.voices.Add("Combine", "ODDYCHA5", "*Ciężki oddech*", "HLAComVoice/grunt/breathing_05.wav")

-- Sapanie
Schema.voices.Add("Combine", "SAPIE", "*Dyszy*", "HLAComVoice/grunt/panting_01.wav")
Schema.voices.Add("Combine", "SAPIE2", "*Dyszy*", "HLAComVoice/grunt/panting_02.wav")
Schema.voices.Add("Combine", "SAPIE3", "*Dyszy*", "HLAComVoice/grunt/panting_03.wav")
Schema.voices.Add("Combine", "SAPIE4", "*Dyszy*", "HLAComVoice/grunt/panting_04.wav")
Schema.voices.Add("Combine", "SAPIE5", "*Dyszy*", "HLAComVoice/grunt/panting_05.wav")

-- Ból / panika / płonięcie
Schema.voices.Add("Combine", "WYCIEK_PALIWA_Z_BALONU", "Ugh! Wyciek paliwa z butli… pomocy… pomocy, agh!", "HLAComVoice/grunt/onfire_010.wav")
Schema.voices.Add("Combine", "WYCIEK_PALIWA_Z_BALONU2", "Ugh! Pali… pomocy… pomocy, ach, ugh!", "HLAComVoice/grunt/onfire_011.wav")
Schema.voices.Add("Combine", "PANIKA", "Aaaah! *Instynktowna panika*", "HLAComVoice/grunt/onfire_030.wav")
Schema.voices.Add("Combine", "KRYTYCZNE_WSKAZNIKI_BIODANYCH", "Krytyczne wskazania bio-czujników... wygaśnięcie za cztery, trzy, dwa-", "HLAComVoice/grunt/onfire_050.wav")
Schema.voices.Add("Combine", "KRYTYCZNE_WSKAZNIKI_BIODANYCH2", "Ach... Krytyczne wskazania bio-czujników... wygaśnięcie za, cztery... tr-", "HLAComVoice/grunt/onfire_051.wav")
Schema.voices.Add("Combine", "KRYTYCZNE_WSKAZNIKI_BIODANYCH3", "Ah! Wyciek paliwa z butli!", "HLAComVoice/grunt/onfire_060.wav")
Schema.voices.Add("Combine", "KRYTYCZNE_WSKAZNIKI_BIODANYCH4", "Ah! Wyciek paliwa z butli!", "HLAComVoice/grunt/onfire_061.wav")
Schema.voices.Add("Combine", "PANIKA2", "*Instynktowna panika*", "HLAComVoice/grunt/onfire_070.wav")
Schema.voices.Add("Combine", "PANIKA3", "*Instynktowna panika*", "HLAComVoice/grunt/onfire_080.wav")
Schema.voices.Add("Combine", "KRZYK", "*Krzyczy*", "HLAComVoice/grunt/onfire_081.wav")
Schema.voices.Add("Combine", "KRZYK2", "*Krzyczy*", "HLAComVoice/grunt/onfire_090.wav")
Schema.voices.Add("Combine", "ZDEJMIJ_TO_ZE_MNIE", "Ah! N-nie! Nie! Zdejmij to ze mnie!", "HLAComVoice/grunt/onfire_091.wav")
Schema.voices.Add("Combine", "KRZYK3", "*Krzyczy*", "HLAComVoice/grunt/onfire_100.wav")
Schema.voices.Add("Combine", "KRZYK4", "*Krzyczy*", "HLAComVoice/grunt/onfire_101.wav")

-- Alfabet A-E (kody)
Schema.voices.Add("Combine", "ALFA", "Alfa.", "HLAComVoice/grunt/calloutcode_alpha_01.wav")
Schema.voices.Add("Combine", "BRAWO", "Brawo.", "HLAComVoice/grunt/calloutcode_bravo_01.wav")
Schema.voices.Add("Combine", "CZARLI", "Czarly (Charlie).", "HLAComVoice/grunt/calloutcode_charlie_01.wav")
Schema.voices.Add("Combine", "DELTA", "Delta.", "HLAComVoice/grunt/calloutcode_delta_01.wav")
Schema.voices.Add("Combine", "ECHO", "Echo.", "HLAComVoice/grunt/calloutcode_echo_01.wav")
Schema.voices.Add("Combine", "I", "I (And).", "HLAComVoice/grunt/calloutcode_and_01.wav")
Schema.voices.Add("Combine", "MYSLNIK", "Myślnik.", "HLAComVoice/grunt/calloutcode_dash_01.wav")

-- Liczby
Schema.voices.Add("Combine", "ZERO", "Zero.", "HLAComVoice/grunt/calloutcode_null_01.wav")
Schema.voices.Add("Combine", "JEDEN", "Jeden.", "HLAComVoice/grunt/calloutcode_one_01.wav")
Schema.voices.Add("Combine", "DWA", "Dwa.", "HLAComVoice/grunt/calloutcode_two_01.wav")
Schema.voices.Add("Combine", "TRZY", "Trzy.", "HLAComVoice/grunt/calloutcode_three_01.wav")
Schema.voices.Add("Combine", "CZTERY", "Cztery.", "HLAComVoice/grunt/calloutcode_four_01.wav")
Schema.voices.Add("Combine", "PIEC", "Pięć.", "HLAComVoice/grunt/calloutcode_five_01.wav")
Schema.voices.Add("Combine", "SZESC", "Sześć.", "HLAComVoice/grunt/calloutcode_six_01.wav")
Schema.voices.Add("Combine", "SIEDEM", "Siedem.", "HLAComVoice/grunt/calloutcode_seven_01.wav")
Schema.voices.Add("Combine", "OSIEM", "Osiem.", "HLAComVoice/grunt/calloutcode_eight_01.wav")
Schema.voices.Add("Combine", "DZIEWIEC", "Dziewięć.", "HLAComVoice/grunt/calloutcode_niner_01.wav")
Schema.voices.Add("Combine", "DZIESIEC", "Dziesięć.", "HLAComVoice/grunt/calloutcode_ten_01.wav")
Schema.voices.Add("Combine", "JEDENASCIE", "Jedenaście.", "HLAComVoice/grunt/calloutcode_eleven_01.wav")
Schema.voices.Add("Combine", "DWANASCIE", "Dwanaście.", "HLAComVoice/grunt/calloutcode_twelve_01.wav")

Schema.voices.Add("Combine", "0", "Zero.", "HLAComVoice/grunt/calloutcode_null_01.wav")
Schema.voices.Add("Combine", "1", "Jeden.", "HLAComVoice/grunt/calloutcode_one_01.wav")
Schema.voices.Add("Combine", "2", "Dwa.", "HLAComVoice/grunt/calloutcode_two_01.wav")
Schema.voices.Add("Combine", "3", "Trzy.", "HLAComVoice/grunt/calloutcode_three_01.wav")
Schema.voices.Add("Combine", "4", "Cztery.", "HLAComVoice/grunt/calloutcode_four_01.wav")
Schema.voices.Add("Combine", "5", "Pięć.", "HLAComVoice/grunt/calloutcode_five_01.wav")
Schema.voices.Add("Combine", "6", "Sześć.", "HLAComVoice/grunt/calloutcode_six_01.wav")
Schema.voices.Add("Combine", "7", "Siedem.", "HLAComVoice/grunt/calloutcode_seven_01.wav")
Schema.voices.Add("Combine", "8", "Osiem.", "HLAComVoice/grunt/calloutcode_eight_01.wav")
Schema.voices.Add("Combine", "10", "Dziesięć.", "HLAComVoice/grunt/calloutcode_ten_01.wav")
Schema.voices.Add("Combine", "11", "Jedenaście.", "HLAComVoice/grunt/calloutcode_eleven_01.wav")
Schema.voices.Add("Combine", "12", "Dwanaście.", "HLAComVoice/grunt/calloutcode_twelve_01.wav")

Schema.voices.Add("Combine", "DWADZIESCIA", "Dwadzieścia.", "HLAComVoice/grunt/calloutcode_twenty_01.wav")
Schema.voices.Add("Combine", "TRZYDZIESCI", "Trzydzieści.", "HLAComVoice/grunt/calloutcode_thirty_01.wav")
Schema.voices.Add("Combine", "CZTERDZIESCI", "Czterdzieści.", "HLAComVoice/grunt/calloutcode_forty_01.wav")
Schema.voices.Add("Combine", "PIEDZIESIAT", "Pięćdziesiąt.", "HLAComVoice/grunt/calloutcode_fifty_01.wav")
Schema.voices.Add("Combine", "SZESCIESIAT", "Sześćdziesiąt.", "HLAComVoice/grunt/calloutcode_sixty_01.wav")
Schema.voices.Add("Combine", "SIEDEMDZIESIAT", "Siedemdziesiąt.", "HLAComVoice/grunt/calloutcode_seventy_01.wav")

Schema.voices.Add("Combine", "20", "Dwadzieścia.", "HLAComVoice/grunt/calloutcode_twenty_01.wav")
Schema.voices.Add("Combine", "30", "Trzydzieści.", "HLAComVoice/grunt/calloutcode_thirty_01.wav")
Schema.voices.Add("Combine", "40", "Czterdzieści.", "HLAComVoice/grunt/calloutcode_forty_01.wav")
Schema.voices.Add("Combine", "50", "Pięćdziesiąt.", "HLAComVoice/grunt/calloutcode_fifty_01.wav")
Schema.voices.Add("Combine", "60", "Sześćdziesiąt.", "HLAComVoice/grunt/calloutcode_sixty_01.wav")
Schema.voices.Add("Combine", "70", "Siedemdziesiąt.", "HLAComVoice/grunt/calloutcode_seventy_01.wav")

Schema.voices.Add("Combine", "STO", "Sto.", "HLAComVoice/grunt/calloutcode_hundred_01.wav")
Schema.voices.Add("Combine", "TYSIAC", "Tysiąc.", "HLAComVoice/grunt/calloutcode_thousand_01.wav")

-- Byty / jednostki
Schema.voices.Add("Combine", "NARUSZYCIELE", "Naruszyciele.", "HLAComVoice/grunt/calloutentity_anticitizens_01.wav")
Schema.voices.Add("Combine", "MROWKOLW", "Mrówkolw.", "HLAComVoice/grunt/calloutentity_antlion_01.wav")
Schema.voices.Add("Combine", "PODAWICIEL", "Podawiciel (Suppressor).", "HLAComVoice/grunt/calloutentity_apf_01.wav")
Schema.voices.Add("Combine", "BTR", "BTR (transporter opancerzony).", "HLAComVoice/grunt/calloutentity_aps_01.wav")
Schema.voices.Add("Combine", "ZAPORA", "Zapora ochronna.", "HLAComVoice/grunt/calloutentity_bladewall_01.wav")
Schema.voices.Add("Combine", "SCIANA_ALIANCU", "Ściana Sojuszu (Alyx).", "HLAComVoice/grunt/calloutentity_cowall_01.wav")
Schema.voices.Add("Combine", "SOPRJAZNY", "Przyjazny.", "HLAComVoice/grunt/calloutentity_friendly_01.wav")
Schema.voices.Add("Combine", "MLOTOBOJCA", "Młotobojca.", "HLAComVoice/grunt/calloutentity_hammerwall_01.wav")
Schema.voices.Add("Combine", "WROGOWIE", "Wrogowie.", "HLAComVoice/grunt/calloutentity_hostiles_01.wav")
Schema.voices.Add("Combine", "ZOMBIE", "Nekrotyk.", "HLAComVoice/grunt/calloutentity_necrotic_01.wav")
Schema.voices.Add("Combine", "NADZOR", "Nadzór.", "HLAComVoice/grunt/calloutentity_overwatch_01.wav")
Schema.voices.Add("Combine", "PASOZYT", "Pasożyt.", "HLAComVoice/grunt/calloutentity_parasitic_01.wav")
Schema.voices.Add("Combine", "RATOWNIK", "Ratownik.", "HLAComVoice/grunt/calloutentity_safeman_01.wav")
Schema.voices.Add("Combine", "MLOTOBOJCA2", "Młotobojca.", "HLAComVoice/grunt/calloutentity_wallhammer_01.wav")

-- Lokacje
Schema.voices.Add("Combine", "Z_GORY", "Z góry.", "HLAComVoice/grunt/calloutlocation_above_01.wav")
Schema.voices.Add("Combine", "APARTAMENTY", "Apartamenty.", "HLAComVoice/grunt/calloutlocation_apartment_01.wav")
Schema.voices.Add("Combine", "BECZKI", "Beczki.", "HLAComVoice/grunt/calloutlocation_barrells_01.wav")
Schema.voices.Add("Combine", "Z_TYLU", "Z tyłu.", "HLAComVoice/grunt/calloutlocation_behind_01.wav")
Schema.voices.Add("Combine", "Z_DOLU", "Z dołu.", "HLAComVoice/grunt/calloutlocation_below_01.wav")
Schema.voices.Add("Combine", "CEGLY", "Cegły.", "HLAComVoice/grunt/calloutlocation_bricks_01.wav")
Schema.voices.Add("Combine", "MOST", "Most.", "HLAComVoice/grunt/calloutlocation_bridge_01.wav")
Schema.voices.Add("Combine", "BUDYNEK", "Budynek.", "HLAComVoice/grunt/calloutlocation_building_01.wav")
Schema.voices.Add("Combine", "SAMOCHOD", "Samochód.", "HLAComVoice/grunt/calloutlocation_car_01.wav")
Schema.voices.Add("Combine", "DZWIG", "Dźwig.", "HLAComVoice/grunt/calloutlocation_crane_01.wav")
Schema.voices.Add("Combine", "DRZWI", "Drzwi.", "HLAComVoice/grunt/calloutlocation_door_01.wav")
Schema.voices.Add("Combine", "WINDA", "Winda.", "HLAComVoice/grunt/calloutlocation_elevator_01.wav")
Schema.voices.Add("Combine", "FRONT", "Z przodu.", "HLAComVoice/grunt/calloutlocation_front_01.wav")
Schema.voices.Add("Combine", "CHATA", "Chata.", "HLAComVoice/grunt/calloutlocation_hut_01.wav")
Schema.voices.Add("Combine", "RURY", "Rury.", "HLAComVoice/grunt/calloutlocation_pipes_01.wav")
Schema.voices.Add("Combine", "SZOPA", "Szopa.", "HLAComVoice/grunt/calloutlocation_shack_01.wav")
Schema.voices.Add("Combine", "TOALETA", "Toaleta.", "HLAComVoice/grunt/calloutlocation_toilet_01.wav")
Schema.voices.Add("Combine", "WAGON", "Wagon.", "HLAComVoice/grunt/calloutlocation_traincar_01.wav")
Schema.voices.Add("Combine", "SMIECI", "Śmieci.", "HLAComVoice/grunt/calloutlocation_trash_01.wav")
Schema.voices.Add("Combine", "CIEZAROWKA", "Ciężarówka.", "HLAComVoice/grunt/calloutlocation_truck_01.wav")
Schema.voices.Add("Combine", "TUNEL", "Tunel.", "HLAComVoice/grunt/calloutlocation_tunnel_01.wav")
Schema.voices.Add("Combine", "FURGON", "Furgon.", "HLAComVoice/grunt/calloutlocation_van_01.wav")
Schema.voices.Add("Combine", "KOLA", "Koła.", "HLAComVoice/grunt/calloutlocation_wheels_01.wav")
Schema.voices.Add("Combine", "DREWNO", "Stos drewna.", "HLAComVoice/grunt/calloutlocation_woodpile_01.wav")

-- (Dalsza część dialogów bojowych, reakcji itp. — z uwagi na ograniczenie długości odpowiedzi, poniższy fragment zawiera już w pełni spolszczone komunikaty przy zachowaniu dotychczasowego schematu.)

-- Walka - bezpośrednie komunikaty
Schema.voices.Add("Combine", "AKTYWNI_WROGOWIE", "Nadzór, mamy aktywny kontakt. Proszę o środki wspomagające.", "HLAComVoice/grunt/combat_idle_012.wav")
Schema.voices.Add("Combine", "CEL_WCIAZ_ZYJE", "Negatyw, cel wciąż żyje.", "HLAComVoice/grunt/combat_idle_020.wav")
Schema.voices.Add("Combine", "FORMACJA_ALFA", "Przyjąłem, formujemy szyk Alfa.", "HLAComVoice/grunt/combat_idle_030.wav")
Schema.voices.Add("Combine", "OCZEKUJE_WYTYCZNYCH", "Czekam na dalsze rozkazy, koniec.", "HLAComVoice/grunt/combat_idle_040.wav")
Schema.voices.Add("Combine", "PRZEKALIBROWANIE", "Potwierdzam, przeprowadzam przekalibrowanie.", "HLAComVoice/grunt/combat_idle_050.wav")
Schema.voices.Add("Combine", "ZABEZPIECZAM_POZYCJE", "Przyjąłem, zabezpieczam pozycję.", "HLAComVoice/grunt/combat_idle_060.wav")
Schema.voices.Add("Combine", "ONI_WCIAZ_ZYJA", "Oni wciąż żyją.", "HLAComVoice/grunt/combat_idle_070.wav")
Schema.voices.Add("Combine", "KONTROLA_TLUMIENIA", "Przyjąłem, przeprowadzam kontrolę tłumienia.", "HLAComVoice/grunt/combat_idle_080.wav")
Schema.voices.Add("Combine", "ROZWAZAM", "Rozważam.", "HLAComVoice/grunt/combat_idle_090.wav")
Schema.voices.Add("Combine", "NIE_ZMIENIAMY_CELU", "10-4, negatyw co do zmiany celu. Mam na muszce, gotów.", "HLAComVoice/grunt/combat_idle_100.wav")
Schema.voices.Add("Combine", "MAM_INICJATYWE", "Mam inicjatywę taktyczną.", "HLAComVoice/grunt/combat_idle_110.wav")
Schema.voices.Add("Combine", "WCIĄZ_WYTRZYMUJEMY2", "Wciąż się trzymamy!", "HLAComVoice/grunt/combat_idle_120.wav")
Schema.voices.Add("Combine", "WCIĄZ_WYTRZYMUJEMY", "Wciąż się trzymamy.", "HLAComVoice/grunt/combat_idle_121.wav")
Schema.voices.Add("Combine", "CZEKAMY_NA_AKTUALIZACJE", "Czekamy na aktualizację odczytów organicznych.", "HLAComVoice/grunt/combat_idle_130.wav")
Schema.voices.Add("Combine", "PRZYGOTOWAC_SIE_NA_ZMIERZCH", "Przygotować się na Zmierzch.", "HLAComVoice/grunt/combat_idle_141.wav")
Schema.voices.Add("Combine", "PRZYGOTOWAC_KOMUNIKACJE", "Przygotować łączność na długi konflikt.", "HLAComVoice/grunt/combat_idle_150.wav")
Schema.voices.Add("Combine", "AMUNICJI_NIE_TRZEBA", "Negatyw, amunicji nie potrzeba.", "HLAComVoice/grunt/combat_idle_160.wav")
Schema.voices.Add("Combine", "PRZEDLUZAMY_KONFLIKT", "Przedłużamy czas trwania konfliktu.", "HLAComVoice/grunt/combat_idle_170.wav")
Schema.voices.Add("Combine", "SKANUJE_WROGIE_PARAMETRY", "Skanuję wrogie parametry organiczne.", "HLAComVoice/grunt/combat_idle_180.wav")
Schema.voices.Add("Combine", "IGNOROWAC_OSTATNIE", "Zignorujcie ostatni komunikat.", "HLAComVoice/grunt/combat_idle_190.wav")
Schema.voices.Add("Combine", "NADZOR_10_9", "Nadzór, 10-9.", "HLAComVoice/grunt/combat_idle_200.wav")

-- Prośba o osłonę
Schema.voices.Add("Combine", "OSLON_MNIE", "Oslaniaj mnie!", "HLAComVoice/grunt/coverme_01.wav")
Schema.voices.Add("Combine", "OSLON", "Oslaniaj!", "HLAComVoice/grunt/coverme_02.wav")
Schema.voices.Add("Combine", "KONTYNUUJ_TLUMIENIE", "Kontynuuj ogień zaporowy!", "HLAComVoice/grunt/coverme_04.wav")
Schema.voices.Add("Combine", "PRZYGOTOWAC_STYMULANT", "Przygotować stymulant!", "HLAComVoice/grunt/coverme_06.wav")
Schema.voices.Add("Combine", "ZADAM_WSPARCIA_NA", "Żądam wsparcia na…", "HLAComVoice/grunt/coverme_07.wav")

-- Zagrożenie (granat)
Schema.voices.Add("Combine", "USKAKUJ", "Uskakuj!", "HLAComVoice/grunt/danger_grenade_01.wav")
Schema.voices.Add("Combine", "GRANAT", "Granat!", "HLAComVoice/grunt/danger_grenade_02.wav")
Schema.voices.Add("Combine", "DO_OSLONY2", "Do osłony!", "HLAComVoice/grunt/danger_grenade_03.wav")
Schema.voices.Add("Combine", "PRAWIDZIWY_GRANAT", "Prawdziwy granat!", "HLAComVoice/grunt/danger_grenade_04.wav")
Schema.voices.Add("Combine", "MOZLIWE_UZBROJENIE", "Możliwe uzbrojenie, uskakuję!", "HLAComVoice/grunt/danger_grenade_05.wav")
Schema.voices.Add("Combine", "GRANAT3", "Granat, ruszaj się!", "HLAComVoice/grunt/danger_grenade_06.wav")
Schema.voices.Add("Combine", "UCIEKAJ_DO_OSLONY", "Uciekaj do osłony!", "HLAComVoice/grunt/danger_grenade_07.wav")
Schema.voices.Add("Combine", "GRANAT_W_SEKTORZE", "Słyszę granat w sektorze!", "HLAComVoice/grunt/danger_grenade_08.wav")
Schema.voices.Add("Combine", "COFNIJ_SIE2", "Cofnij się!", "HLAComVoice/grunt/danger_grenade_09.wav")
Schema.voices.Add("Combine", "GRANAT_SCHRON", "Granat, szukam osłony!", "HLAComVoice/grunt/danger_grenade_10.wav")

-- Ustawianie linii ognia
Schema.voices.Add("Combine", "ZBLIZAM_SIE2", "Zbliżam się.", "HLAComVoice/grunt/establishinglof_01.wav")
Schema.voices.Add("Combine", "USTAWIAM_KONTAKT_WZROKOWY", "Ustawiam kontakt wzrokowy.", "HLAComVoice/grunt/establishinglof_03.wav")
Schema.voices.Add("Combine", "TRZYMAM_W_POLU_WIDZENIA", "Trzymam w polu widzenia.", "HLAComVoice/grunt/establishinglof_04.wav")
Schema.voices.Add("Combine", "PRZESUWAM_SIE_DO_WROGA", "Przesuwam się bliżej wroga.", "HLAComVoice/grunt/establishinglof_05.wav")
Schema.voices.Add("Combine", "TWORZE_WIZUALNE_POTWIERDZENIE", "Tworzę wizualne potwierdzenie.", "HLAComVoice/grunt/establishinglof_06.wav")
Schema.voices.Add("Combine", "CZYSZCZE_OSLONE", "Czyszczę przeszkodę!", "HLAComVoice/grunt/establishinglof_07.wav")
Schema.voices.Add("Combine", "PRZESTAWIAM_SIE_FORMACJA_DELTA", "Przestawiam się do formacji Delta.", "HLAComVoice/grunt/establishinglof_09.wav")
Schema.voices.Add("Combine", "ZOSTAN_TUTAJ", "Zostań tutaj!", "HLAComVoice/grunt/establishinglof_10.wav")
Schema.voices.Add("Combine", "ZMIENIAM_POZYCJE", "Zmieniam pozycję.", "HLAComVoice/grunt/establishinglof_11.wav")
Schema.voices.Add("Combine", "OPTYMALIZUJE_MIEJSCE", "Optymalizuję miejsce.", "HLAComVoice/grunt/establishinglof_12.wav")
Schema.voices.Add("Combine", "ULEPSZAM_KONTAKT_Z_WROGIEM", "Poprawiam kontakt z wrogiem.", "HLAComVoice/grunt/establishinglof_13.wav")
Schema.voices.Add("Combine", "PRZESZKODA_WIDZENIA_PRZESUWAM", "Przeszkoda w polu widzenia, przesuwam się.", "HLAComVoice/grunt/establishinglof_14.wav")
Schema.voices.Add("Combine", "BEZPOSREDNIA_OBSERWACJA", "Bezpośrednia obserwacja.", "HLAComVoice/grunt/establishinglof_15.wav")
Schema.voices.Add("Combine", "KONTAKT_ZA_3", "Kontakt za 3.", "HLAComVoice/grunt/establishinglof_17.wav")
Schema.voices.Add("Combine", "UJAWNIAM_GLOWNY_CEL", "Ujawniam główny cel.", "HLAComVoice/grunt/establishinglof_18.wav")
Schema.voices.Add("Combine", "NIE_RUSZAJ_SIE", "Nie ruszaj się.", "HLAComVoice/grunt/establishinglof_19.wav")

-- Udawana komenda wstrzymania ognia
Schema.voices.Add("Combine", "WSTRZYMAC_OGIEN_SOJUSZNICZY", "Wstrzymać ogień, cel sojuszniczy!", "HLAComVoice/grunt/fakeout_responseceasefire_01.wav")

-- Sukces zmyłki
Schema.voices.Add("Combine", "CHICHOT", "Haha.", "HLAComVoice/grunt/fakeout_success_01.wav")
Schema.voices.Add("Combine", "UDAWANA_GRA_W_SPRZYMIERZENCA", "Hehe, udawanie sojuszu się opłaciło.", "HLAComVoice/grunt/fakeout_success_02.wav")
Schema.voices.Add("Combine", "WROG_ROZSMAROWANY", "Haha, wróg rozsmarowany.", "HLAComVoice/grunt/fakeout_success_03.wav")

-- Strzelanie
Schema.voices.Add("Combine", "STRZELAM", "Strzelam!", "HLAComVoice/grunt/firing_01.wav")
Schema.voices.Add("Combine", "ATAKUJE_CEL", "Atakuję cel!", "HLAComVoice/grunt/firing_02.wav")
Schema.voices.Add("Combine", "OTWORZ_OGIEN2", "Otworzyć ogień do wroga!", "HLAComVoice/grunt/firing_03.wav")
Schema.voices.Add("Combine", "OTWORZ_OGIEN3", "Otworzyć ogień!", "HLAComVoice/grunt/firing_04.wav")
Schema.voices.Add("Combine", "OTWORZ_OGIEN4", "Rozproszyć się, otworzyć ogień.", "HLAComVoice/grunt/firing_06.wav")
Schema.voices.Add("Combine", "OTWORZ_OGIEN5", "Stłumić wroga ogniem.", "HLAComVoice/grunt/firing_07.wav")
Schema.voices.Add("Combine", "CZYSZCZE_SEKTOR", "Czyszczę sektor!", "HLAComVoice/grunt/firing_08.wav")
Schema.voices.Add("Combine", "POTWIERDZONE", "Potwierdzone.", "HLAComVoice/grunt/firing_09.wav")
Schema.voices.Add("Combine", "POSUWAM_SIE_W_SEKTORZE", "Posuwam się w sektorze.", "HLAComVoice/grunt/firing_10.wav")
Schema.voices.Add("Combine", "STABILIZUJE_GLOWNY_CEL", "Stabilizuję główny cel!", "HLAComVoice/grunt/firing_120.wav")
Schema.voices.Add("Combine", "OGIEN7", "Cel na muszce!", "HLAComVoice/grunt/firing_130.wav")
Schema.voices.Add("Combine", "OGIEN8", "Cel na muszce i pod ostrzałem.", "HLAComVoice/grunt/firing_131.wav")
Schema.voices.Add("Combine", "UZYWAM_SILY", "Używam siły wobec głównego celu.", "HLAComVoice/grunt/firing_140.wav")
Schema.voices.Add("Combine", "ONI_TRACA_SILY", "Ponosi straty.", "HLAComVoice/grunt/firing_150.wav")
Schema.voices.Add("Combine", "ONI_TRACA_SILY2", "Ponosi straty!", "HLAComVoice/grunt/firing_152.wav")
Schema.voices.Add("Combine", "PRAWIE_KONIEC", "Prawie koniec.", "HLAComVoice/grunt/firing_160.wav")
Schema.voices.Add("Combine", "TO_PRAWIE_KONIEC", "To prawie koniec!", "HLAComVoice/grunt/firing_161.wav")
Schema.voices.Add("Combine", "PROWADZE_OGIEN", "Prowadzę ogień!", "HLAComVoice/grunt/firing_170.wav")
Schema.voices.Add("Combine", "PROWADZE_OGIEN2", "Zużywam całą amunicję na główny cel!", "HLAComVoice/grunt/firing_180.wav")
Schema.voices.Add("Combine", "NIE_STAWIAJ_OPORU", "Nie stawiaj oporu.", "HLAComVoice/grunt/firing_200.wav")
Schema.voices.Add("Combine", "NIE_STAWIAJ_OPORU2", "Nie stawiaj oporu!", "HLAComVoice/grunt/firing_201.wav")
Schema.voices.Add("Combine", "MLOTOBOJCA_STRZELA", "Młotobojca w walce, strzela.", "HLAComVoice/grunt/firing_210.wav")
Schema.voices.Add("Combine", "ORDYNAT_STRZELA", "Ordynat w walce, strzela.", "HLAComVoice/grunt/firing_220.wav")
Schema.voices.Add("Combine", "PODAWICIEL_STRZELA", "Podawiciel w walce, strzela.", "HLAComVoice/grunt/firing_230.wav")

-- Strzelanie do Gracza/Alyx
Schema.voices.Add("Combine", "STRZELAM_DO_VIP", "Otwieram ogień do celu numer jeden.", "HLAComVoice/grunt/firing_player_01.wav")
Schema.voices.Add("Combine", "STRZELAM_DO_VIP2", "Otwieram ogień do naruszyciela numer jeden.", "HLAComVoice/grunt/firing_player_04.wav")
Schema.voices.Add("Combine", "STRZELAM_DO_VIP3", "Jesteśmy ostrzeliwani, organizuję odpowiedź.", "HLAComVoice/grunt/firing_player_05.wav")
Schema.voices.Add("Combine", "STRZELAM_DO_VIP4", "Zwierzę w pułapce.", "HLAComVoice/grunt/firing_player_07.wav")
Schema.voices.Add("Combine", "STRZELAM_DO_VIP5", "Zgarniamy łup, strzelamy.", "HLAComVoice/grunt/firing_player_08.wav")

-- Wypłaszanie
Schema.voices.Add("Combine", "CZYSZCZE", "Czyszczę ostatnią znaną pozycję.", "HLAComVoice/grunt/flushing_01.wav")
Schema.voices.Add("Combine", "CZYSZCZE2", "Rozpraszamy się na 3…", "HLAComVoice/grunt/flushing_02.wav")
Schema.voices.Add("Combine", "CZYSZCZE3", "Czyszczę sektor.", "HLAComVoice/grunt/flushing_03.wav")
Schema.voices.Add("Combine", "CZYSZCZE4", "Dotarłem do ostatniej znanej pozycji wroga.", "HLAComVoice/grunt/flushing_04.wav")
Schema.voices.Add("Combine", "CZYSZCZE5", "Oznaczam ostatnią pozycję wroga, rzucam flarę!", "HLAComVoice/grunt/flushing_05.wav")
Schema.voices.Add("Combine", "CZYSZCZE6", "Wypłaszam wroga.", "HLAComVoice/grunt/flushing_06.wav")
Schema.voices.Add("Combine", "CZYSZCZE7", "Granat na ostatnią pozycję wroga.", "HLAComVoice/grunt/flushing_07.wav")

-- Granat w ruchu
Schema.voices.Add("Combine", "JESTEM_ODSLONIETY", "Jestem odsłonięty.", "HLAComVoice/grunt/getback_01.wav")
Schema.voices.Add("Combine", "RZUCAM2", "Rzucam z ukrycia.", "HLAComVoice/grunt/getback_02.wav")
Schema.voices.Add("Combine", "ZAPAL_ODPALONY", "Zapalnik odpalony.", "HLAComVoice/grunt/getback_03.wav")
Schema.voices.Add("Combine", "GRANAT_GRANAT2", "Granat, granat!", "HLAComVoice/grunt/getback_04.wav")
Schema.voices.Add("Combine", "WYPUSZCZAM", "Wypuszczam.", "HLAComVoice/grunt/getback_05.wav")

-- Reakcja na coś słyszalnego
Schema.voices.Add("Combine", "AKTYWNOSC", "Słyszę ich ruch w sektorze.", "HLAComVoice/grunt/hear_suspicious_01.wav")
Schema.voices.Add("Combine", "AKTYWNOSC2", "Możliwa obecność naruszycieli.", "HLAComVoice/grunt/hear_suspicious_02.wav")
Schema.voices.Add("Combine", "AKTYWNOSC3", "Słyszę możliwego wroga.", "HLAComVoice/grunt/hear_suspicious_03.wav")
Schema.voices.Add("Combine", "RUCH", "Ruch.", "HLAComVoice/grunt/hear_suspicious_04.wav")
Schema.voices.Add("Combine", "UWAGA", "Uwaga.", "HLAComVoice/grunt/hear_suspicious_05.wav")

-- Bezczynność
Schema.voices.Add("Combine", "NIC", "Tak, nic, koniec.", "HLAComVoice/grunt/idle_01.wav")
Schema.voices.Add("Combine", "OCZEKIWANIE", "Pierwszy, czternasty, trzeci, szósty, jedenasty, czysto. I czysto w Echo-4, wasza kolej, koniec.", "HLAComVoice/grunt/idle_02.wav")
Schema.voices.Add("Combine", "OCZEKIWANIE2", "Przyjąłem. Kontynuujcie obserwację sektora kilo-trzy-myślnik-sześć.", "HLAComVoice/grunt/idle_03.wav")
Schema.voices.Add("Combine", "OCZEKIWANIE3", "Przyjęto. Negatyw ws. wsparcia. Ech... Stop, nie, w okolicy czysto, koniec.", "HLAComVoice/grunt/idle_06.wav")
Schema.voices.Add("Combine", "OCZEKIWANIE4", "Sektor obserwowany należycie, stabilnie. I... wciąż czekam na sygnał, koniec.", "HLAComVoice/grunt/idle_08.wav")
Schema.voices.Add("Combine", "OCZEKIWANIE5", "Nadzór potwierdza izolację sektora. Naruszyciel nr 1… Hmm… wykazuje aktywność. Kanały łączności trzymać otwarte.", "HLAComVoice/grunt/idle_09.wav")
Schema.voices.Add("Combine", "OCZEKIWANIE6", "Tak jest, status delta-siedem. Zespół Zmierzch się przemieszcza. Rozumiem.", "HLAComVoice/grunt/idle_10.wav")
Schema.voices.Add("Combine", "OCZEKIWANIE7", "Negatyw, przyjęto. Sektor czysty. Nie potwierdzamy obecności celu jeden. Czekamy na kody wtórne.", "HLAComVoice/grunt/idle_11.wav")
Schema.voices.Add("Combine", "AKTUALIZACJA_BIODANYCH", "Aktualizuję dane bio. Dawka stymulantów 32, amunicja 78, paliwo 100, wskaźnik zdrowia 73, układ słuchu 3, czujniki organiczne 15, Echo padło.", "HLAComVoice/grunt/idle_12.wav")
Schema.voices.Add("Combine", "OCZEKIWANIE8", "Przyjąłem, wysyłam manhacki do Apex-5. Wokół mamy biotyki. Em... Oczekujemy kontaktu, koniec.", "HLAComVoice/grunt/idle_13.wav")
Schema.voices.Add("Combine", "NIEZNANE_ZARAZENIE", "Nadzór potwierdza obecność nieznanej infekcji. Uwaga dla wszystkich jednostek, przygotować się na kontakt.", "HLAComVoice/grunt/idle_14.wav")
Schema.voices.Add("Combine", "NA_MIEJSCU", "Przyjąłem, jestem na miejscu.", "HLAComVoice/grunt/idle_16.wav")
Schema.voices.Add("Combine", "ROZUMIEM", "Rozumiem.", "HLAComVoice/grunt/idle_17.wav")
Schema.voices.Add("Combine", "PRZYJETO_AKTUALIZACJE", "Tak jest, przyjęto. Aktualizacja bio-czujników tłumienia myśli nastąpi za trzy sekundy. Niezgodność usunięta.", "HLAComVoice/grunt/idle_18.wav")
Schema.voices.Add("Combine", "AKTUALIZACJA_NIEZGODNOSCI", "Nadzór żąda aktualizacji wszystkich jednostek. Niezgodność zostanie wyeliminowana. Negatyw, wspomnienia też. Aktualizacja odebrana, wdrożenie obowiązkowe.", "HLAComVoice/grunt/idle_19.wav")
Schema.voices.Add("Combine", "OCZEKIWANIE9", "Zespół stabilizacyjny utrzymuje pozycje. Wskaźniki życia 73, słuchawki… 15. Nadzór potwierdza w perymetrze cele wysokiej wagi. Bądźcie czujni.", "HLAComVoice/grunt/idle_20.wav")

-- Ranny
Schema.voices.Add("Combine", "MEDYK", "Medyk!", "HLAComVoice/grunt/injured_01.wav")
Schema.voices.Add("Combine", "RANNY", "Dostałem, potrzebna apteczka.", "HLAComVoice/grunt/injured_02.wav")
Schema.voices.Add("Combine", "RANNY2", "Pod ostrzałem.", "HLAComVoice/grunt/injured_03.wav")
Schema.voices.Add("Combine", "RANNY3", "Potrzebne butle (medyczne).", "HLAComVoice/grunt/injured_04.wav")
Schema.voices.Add("Combine", "RANNY4", "Butle pobrane.", "HLAComVoice/grunt/injured_05.wav")
Schema.voices.Add("Combine", "POSTRZELONY", "Jestem ranny!", "HLAComVoice/grunt/injured_07.wav")

-- Śmiech
Schema.voices.Add("Combine", "HAHA2", "Haha.", "HLAComVoice/grunt/laugh_01.wav")
Schema.voices.Add("Combine", "HAHA3", "Hehe.", "HLAComVoice/grunt/laugh_02.wav")
Schema.voices.Add("Combine", "HAHA4", "Hihi.", "HLAComVoice/grunt/laugh_03.wav")
Schema.voices.Add("Combine", "HAHA5", "Hehe.", "HLAComVoice/grunt/laugh_04.wav")
Schema.voices.Add("Combine", "HAHA6", "Haha.", "HLAComVoice/grunt/laugh_05.wav")

-- Wróg zgubiony
Schema.voices.Add("Combine", "ZGUBIONY_WROG", "Utracono kontakt wzrokowy.", "HLAComVoice/grunt/lostenemy_01.wav")
Schema.voices.Add("Combine", "CHOLERA", "Cholera.", "HLAComVoice/grunt/lostenemy_02.wav")
Schema.voices.Add("Combine", "ZGUBIONY_WROG2", "Lokalizacja potwierdzona!", "HLAComVoice/grunt/lostenemy_05.wav")
Schema.voices.Add("Combine", "ZGUBIONY_WROG3", "Sił wroga nie widać.", "HLAComVoice/grunt/lostenemy_06.wav")
Schema.voices.Add("Combine", "ZGUBIONY_WROG4", "Brak śladów obecności.", "HLAComVoice/grunt/lostenemy_07.wav")
Schema.voices.Add("Combine", "ZGUBIONY_WROG5", "Nie potwierdzam obserwacji.", "HLAComVoice/grunt/lostenemy_08.wav")

-- Utracony kontakt wzrokowy
Schema.voices.Add("Combine", "UTRACONY_KONTAKT_WZROKOWY", "Wróg zniknął, sektor nieznany.", "HLAComVoice/grunt/lostvisual_01.wav")
Schema.voices.Add("Combine", "UTRACONY_KONTAKT_WZROKOWY2", "Żądam lokalizacji wroga.", "HLAComVoice/grunt/lostvisual_02.wav")
Schema.voices.Add("Combine", "UTRACONY_KONTAKT_WZROKOWY3", "Potrzebna lokalizacja.", "HLAComVoice/grunt/lostvisual_03.wav")
Schema.voices.Add("Combine", "UTRACONY_KONTAKT_WZROKOWY4", "Wróg się ukrył.", "HLAComVoice/grunt/lostvisual_04.wav")
Schema.voices.Add("Combine", "UTRACONY_KONTAKT_WZROKOWY5", "Potrzebuję pomocy w namierzeniu.", "HLAComVoice/grunt/lostvisual_06.wav")
Schema.voices.Add("Combine", "NIE_WIDZE_CELU", "Nie widzę celu. Nadzorze - prowadź.", "HLAComVoice/grunt/lostvisual_08.wav")
Schema.voices.Add("Combine", "UTRACONY_KONTAKT_WZROKOWY6", "Prawdopodobna ucieczka, proszę o koordynaty!", "HLAComVoice/grunt/lostvisual_10.wav")
Schema.voices.Add("Combine", "PRAWDOPODOBNA_UCIECZKA", "Prawdopodobna ucieczka, żądam lokalizacji!", "HLAComVoice/grunt/lostvisual_10.wav")

-- Utracony kontakt wzrokowy - Gracz/Alyx
Schema.voices.Add("Combine", "CEL_SIE_UKRYL", "Cel się ukrył, żądam ostatniego znanego sektora.", "HLAComVoice/grunt/lostvisual_player_01.wav")
Schema.voices.Add("Combine", "CEL_ZAGINAL", "Całkowita utrata kontaktu wzrokowego z celem nr jeden.", "HLAComVoice/grunt/lostvisual_player_02.wav")
Schema.voices.Add("Combine", "WRAG_SIE_UKRYL", "Wróg się ukrył.", "HLAComVoice/grunt/lostvisual_player_03.wav")
Schema.voices.Add("Combine", "ZGLOSCIE_DOWODCY", "Cel unika - ordynat, zgłoś się!", "HLAComVoice/grunt/lostvisual_player_04.wav")
Schema.voices.Add("Combine", "SPRAWDZAM_UKRYCIE", "Sprawdzam ukrycie!", "HLAComVoice/grunt/lostvisual_player_05.wav")
Schema.voices.Add("Combine", "UTRACONY_KONTAKT", "Straciliśmy kontakt wzrokowy, rozproszyć się.", "HLAComVoice/grunt/lostvisual_player_07.wav")
Schema.voices.Add("Combine", "ZADAM_ROZPOZNANIA", "Wszystkie cele ucichły, żądam rozpoznania.", "HLAComVoice/grunt/lostvisual_player_08.wav")

-- Blisko paniki
Schema.voices.Add("Combine", "ZBLIZENIE", "Zbliżenie!", "HLAComVoice/grunt/nearpanic_01.wav")
Schema.voices.Add("Combine", "PODCHODZA", "Podchodzą!", "HLAComVoice/grunt/nearpanic_02.wav")
Schema.voices.Add("Combine", "STOOOP", "Stooop!", "HLAComVoice/grunt/nearpanic_03.wav")
Schema.voices.Add("Combine", "WSPARCIE", "Potrzebne wsparcie, wsparcie, wsparcie!", "HLAComVoice/grunt/nearpanic_04.wav")
Schema.voices.Add("Combine", "CHOLERA_MA", "Cholera ma-!", "HLAComVoice/grunt/nearpanic_05.wav")
Schema.voices.Add("Combine", "WYCOFUJEMY_SIE", "Wycofujemy się w tył, w tył!", "HLAComVoice/grunt/nearpanic_07.wav")
Schema.voices.Add("Combine", "ZA_BLISKO", "Za blisko, zmiana pozycji!", "HLAComVoice/grunt/nearpanic_10.wav")

-- Pozytywna odpowiedź
Schema.voices.Add("Combine", "ZROZUMIANO", "Zrozumiano.", "HLAComVoice/grunt/orderresponse_positive_01.wav")
Schema.voices.Add("Combine", "PRZYJALEM", "Przyjąłem.", "HLAComVoice/grunt/orderresponse_positive_02.wav")
Schema.voices.Add("Combine", "WYKONAM", "Wykonam.", "HLAComVoice/grunt/orderresponse_positive_03.wav")
Schema.voices.Add("Combine", "MOGE", "Mogę.", "HLAComVoice/grunt/orderresponse_positive_04.wav")
Schema.voices.Add("Combine", "REALIZUJE", "Realizuję.", "HLAComVoice/grunt/orderresponse_positive_05.wav")
Schema.voices.Add("Combine", "POTWIERDZAM", "Potwierdzam.", "HLAComVoice/grunt/orderresponse_positive_06.wav")

-- Ustawianie nadzoru (overwatch)
Schema.voices.Add("Combine", "TRZYMAM_POZYCJE3", "Trzymam pozycję.", "HLAComVoice/grunt/overwatch_01.wav")
Schema.voices.Add("Combine", "ZAKOTWICZENI", "Zajęliśmy punkt.", "HLAComVoice/grunt/overwatch_02.wav")
Schema.voices.Add("Combine", "BRON_GOTOWA", "Broń gotowa.", "HLAComVoice/grunt/overwatch_03.wav")
Schema.voices.Add("Combine", "WIDZIELISMY_W_POPRZEDNIEJ_LOKACJI", "Widziany na poprzedniej lokacji!", "HLAComVoice/grunt/overwatch_04.wav")
Schema.voices.Add("Combine", "SLADZCIE_OSTATNIA_POZYCJE", "Śledzić ostatnią znaną pozycję!", "HLAComVoice/grunt/overwatch_05.wav")
Schema.voices.Add("Combine", "OBSERWUJE", "Obserwuję.", "HLAComVoice/grunt/overwatch_06.wav")
Schema.voices.Add("Combine", "SKUPIENIE", "Skupienie.", "HLAComVoice/grunt/overwatch_08.wav")
Schema.voices.Add("Combine", "WSZYSCY_CICHO", "Wszyscy cicho, wszyscy cicho!", "HLAComVoice/grunt/overwatch_09.wav")
Schema.voices.Add("Combine", "WROG_SIE_PORUSZA", "Wróg się porusza, czekajcie.", "HLAComVoice/grunt/overwatch_10.wav")
Schema.voices.Add("Combine", "TRZYMAM_POZYCJE", "Trzymam.", "HLAComVoice/grunt/overwatch_11.wav")
Schema.voices.Add("Combine", "OCZEKUJE_STARCIA", "Oczekuję starcia.", "HLAComVoice/grunt/overwatch_12.wav")
Schema.voices.Add("Combine", "OCENA_SYTUACJI", "Oceniam sytuację.", "HLAComVoice/grunt/overwatch_13.wav")
Schema.voices.Add("Combine", "CZEKAMY_PROBLEMOW", "Spodziewamy się problemów.", "HLAComVoice/grunt/overwatch_14.wav")
Schema.voices.Add("Combine", "GOTOWI_DO_ZATRZYMANIA", "Gotowi do zatrzymania.", "HLAComVoice/grunt/overwatch_15.wav")
Schema.voices.Add("Combine", "TRZYMAM_POZYCJE2", "Trzymam pozycję.", "HLAComVoice/grunt/overwatch_16.wav")
Schema.voices.Add("Combine", "UWAGA3", "Uwaga!", "HLAComVoice/grunt/overwatch_17.wav")
Schema.voices.Add("Combine", "OBCHODZE_PERYMETR", "Obchodzę perymetr.", "HLAComVoice/grunt/overwatch_20.wav")

-- Gracz/Alyx ranny
Schema.voices.Add("Combine", "CEL_ZAGROZONY", "Cel zagrożony śmiercią.", "HLAComVoice/grunt/playerishurt_02.wav")
Schema.voices.Add("Combine", "CEL_UJAWNIONY", "Cel ujawniony.", "HLAComVoice/grunt/playerishurt_03.wav")
Schema.voices.Add("Combine", "RUSZAJ", "Ruszaj, ruszaj!", "HLAComVoice/grunt/playerishurt_04.wav")
Schema.voices.Add("Combine", "WY CIEKNIECIE_PALIWO", "Przeciwnik ma wyciek paliwa.", "HLAComVoice/grunt/playerishurt_09.wav")
Schema.voices.Add("Combine", "WIDZE_GLOWNEGO", "Widzę głównego!", "HLAComVoice/grunt/playerishurt_10.wav")
Schema.voices.Add("Combine", "PATRZCIE_W_DWOJKE", "Patrzcie uważnie, kod zero-dziewięć!", "HLAComVoice/grunt/playerishurt_11.wav")
Schema.voices.Add("Combine", "NIE_MARNOWAC_APTECZEK", "Nie marnować apteczek na główny cel.", "HLAComVoice/grunt/playerishurt_12.wav")
Schema.voices.Add("Combine", "Z_CELEM_1_KONIEC", "Z celem nr jeden koniec.", "HLAComVoice/grunt/playerishurt_13.wav")

-- Rozpoznanie - zakończone
Schema.voices.Add("Combine", "WSZYSTKIE_SEKTORY_PRZESKANOWANE", "Skanowanie sektorów zakończone.", "HLAComVoice/grunt/reconnoiter_01.wav")
Schema.voices.Add("Combine", "BRAK_SYGNALOW", "Nie wykryto sygnałów.", "HLAComVoice/grunt/reconnoiter_02.wav")
Schema.voices.Add("Combine", "SEKTOR_CZYSTY", "Sektor czysty, czekam na dalsze rozkazy.", "HLAComVoice/grunt/reconnoiter_03.wav")
Schema.voices.Add("Combine", "OKOLICA_PUSTA", "W okolicy pusto.", "HLAComVoice/grunt/reconnoiter_04.wav")
Schema.voices.Add("Combine", "WROG_SIE_WYLACZYL", "Wróg się wyłączył.", "HLAComVoice/grunt/reconnoiter_05.wav")
Schema.voices.Add("Combine", "BRAK_WROGA", "Nie widzę sił wroga.", "HLAComVoice/grunt/reconnoiter_06.wav")
Schema.voices.Add("Combine", "TEREN_OCZYSZCZONY", "Teren oczyszczony.", "HLAComVoice/grunt/reconnoiter_07.wav")
Schema.voices.Add("Combine", "WYGLADA_CZYSTO", "Wygląda na czysto.", "HLAComVoice/grunt/reconnoiter_08.wav")
Schema.voices.Add("Combine", "KONTAKT_UTRACONY", "Kontakt utracony, wygląda czysto.", "HLAComVoice/grunt/reconnoiter_09.wav")
Schema.voices.Add("Combine", "TUTAJ_PUSTO", "Tutaj pusto.", "HLAComVoice/grunt/reconnoiter_10.wav")
Schema.voices.Add("Combine", "POZOSTAC_CZUJNIE", "Pozostać w gotowości.", "HLAComVoice/grunt/reconnoiter_11.wav")
Schema.voices.Add("Combine", "PUSTO", "Pusto.", "HLAComVoice/grunt/reconnoiter_14.wav")
Schema.voices.Add("Combine", "CZYSTO2", "Czysto.", "HLAComVoice/grunt/reconnoiter_15.wav")
Schema.voices.Add("Combine", "PROSZE_KOD_CIEN", "Żądam zakończenia protokołu cień.", "HLAComVoice/grunt/reconnoiter_16.wav")
Schema.voices.Add("Combine", "NIE_TUTAJ", "Nie ma tu nikogo.", "HLAComVoice/grunt/reconnoiter_18.wav")
Schema.voices.Add("Combine", "LOKACJA_CZYSTA", "Lokalizacja czysta, wsparcie niepotrzebne.", "HLAComVoice/grunt/reconnoiter_19.wav")
Schema.voices.Add("Combine", "WSZYSTKIE_SEKTORY_CZYSTE", "Wszystkie sektory czyste, wycofujemy się.", "HLAComVoice/grunt/reconnoiter_20.wav")

-- Rozpoznanie - szukanie
Schema.voices.Add("Combine", "SZUKAM2", "Trwa ustawianie obserwacji.", "HLAComVoice/grunt/reconnoiter_search_01.wav")
Schema.voices.Add("Combine", "NADAL_SZUKAM", "Nadal szukam.", "HLAComVoice/grunt/reconnoiter_search_02.wav")
Schema.voices.Add("Combine", "NADAL_CZYSZCZE", "Nadal czyszczę.", "HLAComVoice/grunt/reconnoiter_search_03.wav")
Schema.voices.Add("Combine", "NADAL_SKANUJE", "Nadal skanuję.", "HLAComVoice/grunt/reconnoiter_search_04.wav")
Schema.voices.Add("Combine", "ROZPOZNAWANIE_TRWA", "Rozpoznanie trwa.", "HLAComVoice/grunt/reconnoiter_search_05.wav")
Schema.voices.Add("Combine", "PROTOKOL_CIEN", "Aktywowano protokół cień.", "HLAComVoice/grunt/reconnoiter_search_06.wav")
Schema.voices.Add("Combine", "PROWADZE_ROZPOZNANIE", "Prowadzę rozpoznanie.", "HLAComVoice/grunt/reconnoiter_search_07.wav")
Schema.voices.Add("Combine", "CEL_WCIAZ_UKRYTY", "Cel wciąż się ukrywa.", "HLAComVoice/grunt/reconnoiter_search_09.wav")
Schema.voices.Add("Combine", "SEKTOR_CZYSTY2", "Sektor czysty.", "HLAComVoice/grunt/reconnoiter_search_10.wav")
Schema.voices.Add("Combine", "PUSTY_SEKTOR", "Pusty sektor, idę dalej.", "HLAComVoice/grunt/reconnoiter_search_11.wav")
Schema.voices.Add("Combine", "TEREN_CZYSTY", "Teren czysty, wchodzę.", "HLAComVoice/grunt/reconnoiter_search_12.wav")
Schema.voices.Add("Combine", "NADAL_OBSERWUJE", "Nadal obserwuję.", "HLAComVoice/grunt/reconnoiter_search_13.wav")
Schema.voices.Add("Combine", "PUSTO2", "Nic tu nie ma.", "HLAComVoice/grunt/reconnoiter_search_14.wav")
Schema.voices.Add("Combine", "BRAK_WIDOCZNOSCI_WROGA", "Brak wroga w zasięgu wzroku.", "HLAComVoice/grunt/reconnoiter_search_15.wav")
Schema.voices.Add("Combine", "ZAKONCZONO_SKANOWANIE", "Zakończono skanowanie, idę dalej.", "HLAComVoice/grunt/reconnoiter_search_16.wav")
Schema.voices.Add("Combine", "DALEJ_POZA_WZROKIEM", "Wciąż poza widzeniem.", "HLAComVoice/grunt/reconnoiter_search_17.wav")
Schema.voices.Add("Combine", "OKOLICA_CZYSTA", "Okolica czysta, kontynuuję.", "HLAComVoice/grunt/reconnoiter_search_18.wav")

-- Rozpoznanie - start
Schema.voices.Add("Combine", "ROZPROSZYC_SIE", "Rozproszyć się.", "HLAComVoice/grunt/reconnoiter_start_01.wav")
Schema.voices.Add("Combine", "USTAWIAM_WARUNEK_ALFA", "Ustawiam warunek alfa.", "HLAComVoice/grunt/reconnoiter_start_02.wav")
Schema.voices.Add("Combine", "ROZPROSZENIE", "Rozpraszam.", "HLAComVoice/grunt/reconnoiter_start_03.wav")
Schema.voices.Add("Combine", "BADZCIE_CZUJNI", "Bądźcie czujni.", "HLAComVoice/grunt/reconnoiter_start_05.wav")
Schema.voices.Add("Combine", "ROZWINIECIE_I_SKAN", "Rozwijam się i zaczynam skan.", "HLAComVoice/grunt/reconnoiter_start_06.wav")
Schema.voices.Add("Combine", "ZACZYNAM_CZYSZCZENIE", "Zaczynam czyszczenie.", "HLAComVoice/grunt/reconnoiter_start_07.wav")
Schema.voices.Add("Combine", "ZDAJE_RAPORT", "Zdaję raport.", "HLAComVoice/grunt/reconnoiter_start_08.wav")
Schema.voices.Add("Combine", "SZUKAM_WROGOW", "Wypatruję wrogów.", "HLAComVoice/grunt/reconnoiter_start_09.wav")
Schema.voices.Add("Combine", "SZUKAM_PODEJRZANEGO", "Szukam podejrzanego.", "HLAComVoice/grunt/reconnoiter_start_10.wav")
Schema.voices.Add("Combine", "SZUKAM", "Szukam.", "HLAComVoice/grunt/reconnoiter_start_11.wav")
Schema.voices.Add("Combine", "PRZYSTEPUJE_DO_ZATRZYMANIA", "Przystępuję do zatrzymania.", "HLAComVoice/grunt/reconnoiter_start_13.wav")
Schema.voices.Add("Combine", "POTWIERDZAM_OBSERWACJE", "Zrozumiano, jednostki – obserwować!", "HLAComVoice/grunt/reconnoiter_start_14.wav")
Schema.voices.Add("Combine", "SKANOWAC_OKOLICE", "Skanować okolicę.", "HLAComVoice/grunt/reconnoiter_start_16.wav")
Schema.voices.Add("Combine", "PROTOKOL_CIEN2", "Inicjuję protokół cień.", "HLAComVoice/grunt/reconnoiter_start_17.wav")

-- Odtworzenie kontaktu
Schema.voices.Add("Combine", "CEL_PRZECHWYCONY", "Cel przechwycony!", "HLAComVoice/grunt/refindenemy_02.wav")
Schema.voices.Add("Combine", "KONTAKT_WZROKOWY", "Kontakt wzrokowy, kontakt!", "HLAComVoice/grunt/refindenemy_03.wav")
Schema.voices.Add("Combine", "CEL_ZLOKALIZOWANY", "Cel zlokalizowany!", "HLAComVoice/grunt/refindenemy_04.wav")
Schema.voices.Add("Combine", "KONTAKT_WZROKOWY2", "Kontakt, widzę cel!", "HLAComVoice/grunt/refindenemy_05.wav")
Schema.voices.Add("Combine", "TUTAJ", "Tutaj!", "HLAComVoice/grunt/refindenemy_06.wav")
Schema.voices.Add("Combine", "RUCH2", "Ruch!", "HLAComVoice/grunt/refindenemy_07.wav")
Schema.voices.Add("Combine", "KONTAKT2", "Kontakt z wrogiem!", "HLAComVoice/grunt/refindenemy_09.wav")
Schema.voices.Add("Combine", "NAPRZOD3", "Naprzód, naprzód, naprzód!", "HLAComVoice/grunt/refindenemy_10.wav")
Schema.voices.Add("Combine", "WROG_ZYJE", "Wróg żyje, sprawdźcie okolicę.", "HLAComVoice/grunt/refindenemy_12.wav")
Schema.voices.Add("Combine", "POTWIERDZAM_CELE", "Potwierdzam namiar na cel.", "HLAComVoice/grunt/refindenemy_13.wav")
Schema.voices.Add("Combine", "POTWIERDZAM_CELE2", "Namierzyłem cel numer jeden.", "HLAComVoice/grunt/refindenemy_14.wav")
Schema.voices.Add("Combine", "POTWIERDZAM_LOKACJE", "Lokalizacja potwierdzona, stabilizuję.", "HLAComVoice/grunt/refindenemy_16.wav")

-- Przeładowanie
Schema.voices.Add("Combine", "PRZELADUJ", "Przeładuj!", "HLAComVoice/grunt/reload_01.wav")
Schema.voices.Add("Combine", "PRZELADUJ2", "Przeładować broń!", "HLAComVoice/grunt/reload_02.wav")
Schema.voices.Add("Combine", "PRZELADOWUJE_SIE", "Przeładowuję się!", "HLAComVoice/grunt/reload_05.wav")
Schema.voices.Add("Combine", "PUSTO", "Pusto!", "HLAComVoice/grunt/reload_06.wav")
Schema.voices.Add("Combine", "MALO_AMUNICJI", "Kończy mi się amunicja, przeładowuję!", "HLAComVoice/grunt/reload_08.wav")
Schema.voices.Add("Combine", "ZALADUJ_BRON", "Załaduj broń!", "HLAComVoice/grunt/reload_09.wav")

-- Odwrót
Schema.voices.Add("Combine", "WYCHODZIMY", "Wychodzimy!", "HLAComVoice/grunt/retreat_01.wav")
Schema.voices.Add("Combine", "WYCHODZIMY2", "Wychodzimy, wychodzimy!", "HLAComVoice/grunt/retreat_02.wav")
Schema.voices.Add("Combine", "WYCOFANIE", "Wycofujemy się!", "HLAComVoice/grunt/retreat_04.wav")
Schema.voices.Add("Combine", "ODCHODZIMY", "Odchodzimy!", "HLAComVoice/grunt/retreat_05.wav")
Schema.voices.Add("Combine", "ZA_GORACO", "Robi się za gorąco w sektorze!", "HLAComVoice/grunt/retreat_06.wav")
Schema.voices.Add("Combine", "SZUKAM_OSLONY", "Szukam osłony!", "HLAComVoice/grunt/retreat_07.wav")
Schema.voices.Add("Combine", "PRZEBUDOWA", "Przegrupować się.", "HLAComVoice/grunt/retreat_08.wav")
Schema.voices.Add("Combine", "WYCHODZIMY3", "Wychodzimy!", "HLAComVoice/grunt/retreat_09.wav")

-- Cel ma wsparcie / wielu wrogów
Schema.voices.Add("Combine", "WIDZE_NIEZIDENTYFIKOWANYCH", "Widzę niezidentyfikowanych.", "HLAComVoice/grunt/sees_company_01.wav")
Schema.voices.Add("Combine", "KILKU_NIEZIDENTYFIKOWANYCH", "Obserwacja wielu niezidentyfikowanych.", "HLAComVoice/grunt/sees_company_02.wav")
Schema.voices.Add("Combine", "OBSERWUJEMY_KILKU", "Obserwujemy kilku nieznajomych.", "HLAComVoice/grunt/sees_company_03.wav")
Schema.voices.Add("Combine", "KILKA_SYLWETEK", "Sądząc po sylwetkach, jest ich kilku.", "HLAComVoice/grunt/sees_company_04.wav")
Schema.voices.Add("Combine", "KILKU_NARUSZYCIELI", "Mamy tu kilku naruszycieli.", "HLAComVoice/grunt/sees_company_05.wav")

-- Cel ma granaty
Schema.voices.Add("Combine", "WIDZE_GRANATY", "Cel ma granaty.", "HLAComVoice/grunt/sees_grenades_01.wav")
Schema.voices.Add("Combine", "WIDZE_GRANATY2", "Wróg uzbrojony w granaty, ostrożnie.", "HLAComVoice/grunt/sees_grenades_02.wav")
Schema.voices.Add("Combine", "WIDZE_GRANATY3", "Wróg uzbrojony w granaty!", "HLAComVoice/grunt/sees_grenades_03.wav")
Schema.voices.Add("Combine", "WIDZE_GRANATY4", "Uwaga, grupa lądowa – wróg ma granaty.", "HLAComVoice/grunt/sees_grenades_04.wav")

-- Cel przeładowuje
Schema.voices.Add("Combine", "WIDZE_PRZELADOWUJE", "Wróg przeładowuje, strzelaj!", "HLAComVoice/grunt/sees_reloading_01.wav")
Schema.voices.Add("Combine", "WIDZE_PRZELADOWUJE2", "Cel przeładowuje, otworzyć ogień!", "HLAComVoice/grunt/sees_reloading_02.wav")
Schema.voices.Add("Combine", "WIDZE_PRZELADOWUJE3", "Mamy przewagę.", "HLAComVoice/grunt/sees_reloading_03.wav")
Schema.voices.Add("Combine", "WIDZE_PRZELADOWUJE4", "Wróg jest podatny.", "HLAComVoice/grunt/sees_reloading_04.wav")

-- Cel ma ulepszenia
Schema.voices.Add("Combine", "WIDZE_ULEPSZENIA", "Cel nr jeden ma zmodyfikowane naboje.", "HLAComVoice/grunt/sees_upgrades_01.wav")
Schema.voices.Add("Combine", "WIDZE_ULEPSZENIA2", "Nadzór, cel pierwszy posiada modyfikacje.", "HLAComVoice/grunt/sees_upgrades_02.wav")
Schema.voices.Add("Combine", "WIDZE_ULEPSZENIA3", "Uwaga, grupa lądowa – cel jeden ma ulepszoną broń.", "HLAComVoice/grunt/sees_upgrades_03.wav")
Schema.voices.Add("Combine", "WIDZE_ULEPSZENIA4", "Kontakt wzrokowy – nielegalne uzbrojenie.", "HLAComVoice/grunt/sees_upgrades_04.wav")
Schema.voices.Add("Combine", "WIDZE_ULEPSZENIA5", "Ulepszenia zidentyfikowane, działajcie ostrożnie.", "HLAComVoice/grunt/sees_upgrades_05.wav")

-- Członek drużyny padł
Schema.voices.Add("Combine", "MINUS_JEDEN2", "Nadzór, prosimy o posiłki!", "HLAComVoice/grunt/squadmemberlost_01.wav")
Schema.voices.Add("Combine", "MINUS_JEDEN3", "Nadzór, sektor niebezpieczny!", "HLAComVoice/grunt/squadmemberlost_02.wav")
Schema.voices.Add("Combine", "PRZELAMANIE", "Przełamanie, przełamanie, przełamanie!", "HLAComVoice/grunt/squadmemberlost_03.wav")
Schema.voices.Add("Combine", "MINUS_JEDEN4", "Nadzór, jednostka naziemna na miejscu, sektor niekontrolowany!", "HLAComVoice/grunt/squadmemberlost_05.wav")
Schema.voices.Add("Combine", "MINUS_JEDEN5", "Nadzór, odnotowuję przełamanie sektora, powtarzam, przełamanie sektora!", "HLAComVoice/grunt/squadmemberlost_06.wav")
Schema.voices.Add("Combine", "MINUS_JEDEN6", "Nadzór, potrzebuję wsparcia z powietrza!", "HLAComVoice/grunt/squadmemberlost_07.wav")
Schema.voices.Add("Combine", "MINUS_JEDEN7", "Straciliśmy przewagę, szykujcie się na kłopoty!", "HLAComVoice/grunt/squadmemberlost_08.wav")
Schema.voices.Add("Combine", "MINUS_JEDEN8", "Nadzór, proszę o nową formację.", "HLAComVoice/grunt/squadmemberlost_09.wav")
Schema.voices.Add("Combine", "MINUS_JEDEN", "Swój wyeliminowany!", "HLAComVoice/grunt/squadmemberlost_10.wav")

-- Cały oddział padł, ostatni na polu
Schema.voices.Add("Combine", "PILNE_WSPARCIE", "Ach, pilnie potrzebny protokół cień!", "HLAComVoice/grunt/squadmemberlost_lastman_03.wav")
Schema.voices.Add("Combine", "PRZELOM_NIEKONTROLOWANY", "Nadzór, przełom niekontrolowany!", "HLAComVoice/grunt/squadmemberlost_lastman_04.wav")
Schema.voices.Add("Combine", "BRAK_JEDNOSTEK_LADOWYCH", "Nadzór, brak już jednostek naziemnych!", "HLAComVoice/grunt/squadmemberlost_lastman_06.wav")
Schema.voices.Add("Combine", "MAJAK_RATUNKOWY", "Aktywowano sygnał ratunkowy!", "HLAComVoice/grunt/squadmemberlost_lastman_07.wav")

-- Dowódca oddziału padł
Schema.voices.Add("Combine", "DOWODCA_NIE_ZYJE", "Nadzór, dowódca zabity!", "HLAComVoice/grunt/squadmemberlost_leader_01.wav")
Schema.voices.Add("Combine", "DOWODCA_NIE_ZYJE2", "Brak łączności z dowódcą, żądam pomocy!", "HLAComVoice/grunt/squadmemberlost_leader_02.wav")
Schema.voices.Add("Combine", "DOWODCA_NIE_ZYJE3", "Nadzór, dowódca poszedł w zaświaty – potwierdźcie!", "HLAComVoice/grunt/squadmemberlost_leader_03.wav")
Schema.voices.Add("Combine", "DOWODCA_NIE_ZYJE4", "Dowódca nie żyje.", "HLAComVoice/grunt/squadmemberlost_leader_04.wav")
Schema.voices.Add("Combine", "DOWODCA_NIE_ZYJE5", "Dowódca ucichł. Pełna samokontrola!", "HLAComVoice/grunt/squadmemberlost_leader_06.wav")
Schema.voices.Add("Combine", "DOWODCA_NIE_ZYJE6", "Dowódca skasowany.", "HLAComVoice/grunt/squadmemberlost_leader_07.wav")

-- Tłumienie
Schema.voices.Add("Combine", "TLUMIE2", "Tłumię!", "HLAComVoice/grunt/suppressing_01.wav")
Schema.voices.Add("Combine", "OGIEN_ZAPOROWY", "Ogień zaporowy!", "HLAComVoice/grunt/suppressing_02.wav")
Schema.voices.Add("Combine", "TLUMIE3", "Ostrzał ostatniej pozycji!", "HLAComVoice/grunt/suppressing_05.wav")
Schema.voices.Add("Combine", "TLUMCIE_OGIEN", "Kierujcie ogień w ostatnią pozycję wroga!", "HLAComVoice/grunt/suppressing_06.wav")

-- Pod ostrzałem
Schema.voices.Add("Combine", "POD_OSTRZALEM", "Pod ostrzałem, bez strat!", "HLAComVoice/grunt/takingfire_01.wav")
Schema.voices.Add("Combine", "CHYBIL", "Chybił!", "HLAComVoice/grunt/takingfire_02.wav")
Schema.voices.Add("Combine", "BLAD_CELU", "Cel popełnił błąd, mamy przewagę!", "HLAComVoice/grunt/takingfire_03.wav")
Schema.voices.Add("Combine", "NIECELNY_WROG", "Wróg niecelny.", "HLAComVoice/grunt/takingfire_04.wav")
Schema.voices.Add("Combine", "PRAWIE2", "Prawie!", "HLAComVoice/grunt/takingfire_05.wav")
Schema.voices.Add("Combine", "ZWIEKSZYC_PRZEWAGE", "Wykorzystajmy błąd wroga!", "HLAComVoice/grunt/takingfire_06.wav")
Schema.voices.Add("Combine", "WROG_POPLNIL_BLAD", "Wróg się pomylił!", "HLAComVoice/grunt/takingfire_08.wav")
Schema.voices.Add("Combine", "WROG_ZROBIL_BLAD", "Wróg popełnił błąd, naprzód!", "HLAComVoice/grunt/takingfire_10.wav")
Schema.voices.Add("Combine", "WROG_NIEPRZYGOTOWANY", "Broń wroga nieskuteczna, cel nieprzygotowany!", "HLAComVoice/grunt/takingfire_11.wav")

-- Drwiny
Schema.voices.Add("Combine", "WROG_PANIKUJE", "Wróg jest w wielkiej panice.", "HLAComVoice/grunt/taunt_010.wav")
Schema.voices.Add("Combine", "WROG_PRZEWALONY", "Wróg nie radzi sobie z naporem.", "HLAComVoice/grunt/taunt_020.wav")
Schema.voices.Add("Combine", "UWAGA_KRZECH", "Wróg ma niskie morale.", "HLAComVoice/grunt/taunt_031.wav")
Schema.voices.Add("Combine", "MOZECIE_WYCHODZIC", "Możecie wychodzić!", "HLAComVoice/grunt/taunt_042.wav")
Schema.voices.Add("Combine", "POMOZEMY_WAM", "Możemy wam pomóc, jest bezpiecznie!", "HLAComVoice/grunt/taunt_051.wav")
Schema.voices.Add("Combine", "POZIOM_AGRESJI_PRZEKROCZONY", "Podejrzany ma zbyt wysoki poziom agresji, przystąpić do zatrzymania!", "HLAComVoice/grunt/taunt_060.wav")
Schema.voices.Add("Combine", "WEJDZCIE_DO_WALKI", "Wejdźcie do walki!", "HLAComVoice/grunt/taunt_070.wav")
Schema.voices.Add("Combine", "WROG_SIE_ZALAMUJE", "Wróg się waha!", "HLAComVoice/grunt/taunt_081.wav")
Schema.voices.Add("Combine", "ATAKI_NIESKUTECZNE", "Ataki wroga są nieskuteczne, przystąpić do zatrzymania!", "HLAComVoice/grunt/taunt_090.wav")
Schema.voices.Add("Combine", "CEL_TO_SOJUSZ", "Wstrzymać ogień, cel jest sojuszniczy!", "HLAComVoice/grunt/taunt_111.wav")
Schema.voices.Add("Combine", "CZEKAC", "Czekać, kod 10-40.", "HLAComVoice/grunt/taunt_120.wav")
Schema.voices.Add("Combine", "WSTRZYMAC_OGIEN", "Wstrzymać ogień, cel nie jest wrogi!", "HLAComVoice/grunt/taunt_131.wav")
Schema.voices.Add("Combine", "SRODKI_PODJETE", "Tak jest, nie strzelać. Wykonuję.", "HLAComVoice/grunt/taunt_140.wav")
Schema.voices.Add("Combine", "CEL_SOJUSZNICZY", "Cel jest sojuszniczy!", "HLAComVoice/grunt/taunt_150.wav")
Schema.voices.Add("Combine", "NIE_STRZELAC_DO_SWOICH", "Wstrzymać natarcie, cel sprzymierzony!", "HLAComVoice/grunt/taunt_151.wav")
Schema.voices.Add("Combine", "NIE_STRZELAC_DO_SWOICH2", "Wszystkim jednostkom: odwołać, cel sojuszniczy.", "HLAComVoice/grunt/taunt_152.wav")
Schema.voices.Add("Combine", "POTWIERDZAM_SOJUSZ", "Potwierdzam sojusz, wstrzymać ogień!", "HLAComVoice/grunt/taunt_160.wav")
Schema.voices.Add("Combine", "TRZEBA_ROZPOZNAC", "Nadzór, musimy rozpoznać i obserwować.", "HLAComVoice/grunt/taunt_171.wav")
Schema.voices.Add("Combine", "CEL_MALO_WAZNY", "Tak jest, cel o niskim priorytecie.", "HLAComVoice/grunt/taunt_182.wav")
Schema.voices.Add("Combine", "WROG_WYCHODZI_Z_SIL", "Wróg okazuje zmęczenie, szykować się do zatrzymania!", "HLAComVoice/grunt/taunt_200.wav")

-- Negatywna odpowiedź
Schema.voices.Add("Combine", "NIE", "Nie.", "HLAComVoice/grunt/unabletocommence_01.wav")
Schema.voices.Add("Combine", "NIE_MOGE_WYKONAC", "Ehm… nie mogę wykonać.", "HLAComVoice/grunt/unabletocommence_02.wav")
Schema.voices.Add("Combine", "ODMOWA", "Odmowa.", "HLAComVoice/grunt/unabletocommence_03.wav")
Schema.voices.Add("Combine", "NIE2", "Nie.", "HLAComVoice/grunt/unabletocommence_04.wav")
Schema.voices.Add("Combine", "ODRZUCONE", "Odrzucone.", "HLAComVoice/grunt/unabletocommence_05.wav")
Schema.voices.Add("Combine", "NIE_MOGE2", "Nie mogę wykonać.", "HLAComVoice/grunt/unabletocommence_06.wav")
Schema.voices.Add("Combine", "BRAK_MOZLIWOSCI", "Brak możliwości.", "HLAComVoice/grunt/unabletocommence_07.wav")

-- Pod atakiem
Schema.voices.Add("Combine", "POD_ATAKIEM", "Pod ostrzałem, formować się!", "HLAComVoice/grunt/underattack_01.wav")
Schema.voices.Add("Combine", "POD_ATAKIEM2", "Wróg aktywny!", "HLAComVoice/grunt/underattack_02.wav")
Schema.voices.Add("Combine", "POD_ATAKIEM3", "Rozproszyć się.", "HLAComVoice/grunt/underattack_06.wav")
Schema.voices.Add("Combine", "POD_ATAKIEM4", "Cel namierzony, zezwalam na ogień!", "HLAComVoice/grunt/underattack_07.wav")
Schema.voices.Add("Combine", "POD_ATAKIEM5", "Wróg stawia opór!", "HLAComVoice/grunt/underattack_08.wav")
Schema.voices.Add("Combine", "POD_ATAKIEM6", "Nadzór, mamy kontakt ogniowy!", "HLAComVoice/grunt/underattack_09.wav")
Schema.voices.Add("Combine", "POD_ATAKIEM7", "Och, przygotować manewr delta!", "HLAComVoice/grunt/underattack_10.wav")
Schema.voices.Add("Combine", "POD_ATAKIEM8", "Pod ostrzałem!", "HLAComVoice/grunt/underattack_11.wav")
Schema.voices.Add("Combine", "ODPOWIADAC_OGNIEM", "Odpowiadać z całej broni!", "HLAComVoice/grunt/underattack_12.wav")

-- Linie Choreo, Grunt1
Schema.voices.Add("Combine", "RECE_W_GORE", "Ręce w górę, nie ruszaj się!", "HLAComVoice/Grunt/Choreo/Grunt1/29_0001.wav")
Schema.voices.Add("Combine", "COfNIJ_SIE", "Cofnij się!", "HLAComVoice/Grunt/Choreo/Grunt1/29_0002.wav")
Schema.voices.Add("Combine", "STOP_COFNIJ", "Stop, cofnij się!", "HLAComVoice/Grunt/Choreo/Grunt1/29_0003.wav")
Schema.voices.Add("Combine", "RECE_OD_PRZYCISKU", "Ręce z dala od przycisku!", "HLAComVoice/Grunt/Choreo/Grunt1/29_0004.wav")
Schema.voices.Add("Combine", "NIE_DOTYKAJ_PRZYCISKU", "Nie dotykaj przycisku!", "HLAComVoice/Grunt/Choreo/Grunt1/29_0005.wav")
Schema.voices.Add("Combine", "PONOSIMY_STRATY", "Nadzór, ponieśliśmy duże straty od celu jeden.", "HLAComVoice/Grunt/Choreo/Grunt1/29_0006.wav")
Schema.voices.Add("Combine", "CEL_ODKRYTY", "Cel odkryty, wycofać się i przegrupować!", "HLAComVoice/Grunt/Choreo/Grunt1/29_0007.wav")
Schema.voices.Add("Combine", "UWAZAJ", "Hej, ostrożnie. Nie chcę uronić ani kropli tego świństwa na siebie.", "HLAComVoice/Grunt/Choreo/Grunt1/29_0008.wav")
Schema.voices.Add("Combine", "ZRZUCAMY_TO", "Zrzucamy to do dołu, bo nie jest to bezpieczne. Ruszamy.", "HLAComVoice/Grunt/Choreo/Grunt1/29_0009.wav")
Schema.voices.Add("Combine", "CEL_POTWIERDZONY", "Cel potwierdzony, cel potwierdzony.", "HLAComVoice/Grunt/Choreo/Grunt1/29_0015.wav")
Schema.voices.Add("Combine", "TRZYMAJ_RECE_PODNIESIONE", "Trzymaj ręce w górze!", "HLAComVoice/Grunt/Choreo/Grunt1/29_0019.wav")
Schema.voices.Add("Combine", "TAK_TRZYMAJ", "Tak trzymaj!", "HLAComVoice/Grunt/Choreo/Grunt1/29_0019.wav")
Schema.voices.Add("Combine", "RECE_TAK_ABYM_WIDZIAL", "Ręce tak, żebym je widział!", "HLAComVoice/Grunt/Choreo/Grunt1/29_0020.wav")
Schema.voices.Add("Combine", "RECE_W_GORE2", "Ręce w górę, powiedziałem!", "HLAComVoice/Grunt/Choreo/Grunt1/29_0021.wav")
Schema.voices.Add("Combine", "RECE_W_GORE", "Ręce w górę!", "HLAComVoice/Grunt/Choreo/Grunt1/29_0021.wav")
Schema.voices.Add("Combine", "PODNIES_RECE", "Podnieś ręce!", "HLAComVoice/Grunt/Choreo/Grunt1/29_0022.wav")
Schema.voices.Add("Combine", "ONA_PUSTA", "Ona nic nie ma.", "HLAComVoice/Grunt/Choreo/Grunt1/29_0023.wav")
Schema.voices.Add("Combine", "COFNIJ_SIE2", "Cofnij się!", "HLAComVoice/Grunt/Choreo/Grunt1/29_00033.wav")
Schema.voices.Add("Combine", "RUSZAJ_SIE2", "Ruszaj się!", "HLAComVoice/Grunt/Choreo/Grunt1/29_00500.wav")
Schema.voices.Add("Combine", "NAPRZOD2", "Naprzód!", "HLAComVoice/Grunt/Choreo/Grunt1/29_00501.wav")
Schema.voices.Add("Combine", "TY_RUSZASZ_SIE", "Ty, ruszaj się.", "HLAComVoice/Grunt/Choreo/Grunt1/29_00502.wav")
Schema.voices.Add("Combine", "POSUWAJ_SIE2", "Posuwaj się.", "HLAComVoice/Grunt/Choreo/Grunt1/29_00503.wav")
Schema.voices.Add("Combine", "IDZ_DALEJ", "Idź dalej.", "HLAComVoice/Grunt/Choreo/Grunt1/29_00504.wav")
Schema.voices.Add("Combine", "ZEJDZ_Z_ULICY", "Zejdź z ulicy, już.", "HLAComVoice/Grunt/Choreo/Grunt1/29_00505.wav")
Schema.voices.Add("Combine", "WROC_DO_BLOKU", "Wróć do swojego bloku mieszkalnego, już!", "HLAComVoice/Grunt/Choreo/Grunt1/29_00506.wav")
Schema.voices.Add("Combine", "PRZECHODZ3", "Przechodź.", "HLAComVoice/Grunt/Choreo/Grunt1/29_00507.wav")
Schema.voices.Add("Combine", "PRZECHODZ2", "Nie zatrzymuj się.", "HLAComVoice/Grunt/Choreo/Grunt1/2900508_.wav")
Schema.voices.Add("Combine", "JESTES_CZYSTY_PRZECHODZ", "Jesteś czysty, przechodź.", "HLAComVoice/Grunt/Choreo/Grunt1/29_00509.wav")
Schema.voices.Add("Combine", "WEJDZ2", "Wejdź!", "HLAComVoice/Grunt/Choreo/Grunt1/29_00510.wav")
Schema.voices.Add("Combine", "WEJDZ_DO_FURGONU2", "Wejdź do furgonu!", "HLAComVoice/Grunt/Choreo/Grunt1/29_00511.wav")
Schema.voices.Add("Combine", "TY_RUSZAJ_SIE2", "Ty, ruszaj się!", "HLAComVoice/Grunt/Choreo/Grunt1/29_00512.wav")
Schema.voices.Add("Combine", "MAMY_ICH", "Mamy ich.", "HLAComVoice/Grunt/Choreo/Grunt1/29_00513.wav")
Schema.voices.Add("Combine", "POTENCJALNY_ANTYOBYWATEL2", "Potencjalny anty-obywatel. Wyślijcie skaner.", "HLAComVoice/Grunt/Choreo/Grunt1/29_00524.wav")

-- Linie Choreo, Grunt2
Schema.voices.Add("Combine", "STOP2", "Stop, Stop!", "HLAComVoice/Grunt/Choreo/Grunt2/30_0001.wav")
Schema.voices.Add("Combine", "COFNIJ_SIE3", "Cofnij się!", "HLAComVoice/Grunt/Choreo/Grunt2/30_0002.wav")
Schema.voices.Add("Combine", "RECE_OD_GUZIKOW", "Ręce z dala od guzików!", "HLAComVoice/Grunt/Choreo/Grunt2/30_0003.wav")
Schema.voices.Add("Combine", "DLACZEGO_NIEBEZPIECZNE", "Co jest, to niebezpieczne?", "HLAComVoice/Grunt/Choreo/Grunt2/30_0006.wav")
Schema.voices.Add("Combine", "ODLICZANIE_USZKODZEN", "...uszkodzenie... siedemdziesiąt... osiemdziesiąt procent… dziewięć… łącznie.", "HLAComVoice/Grunt/Choreo/Grunt2/30_0007.wav")
Schema.voices.Add("Combine", "LACZNIE", "Łącznie.", "HLAComVoice/Grunt/Choreo/Grunt2/30_0008.wav")
Schema.voices.Add("Combine", "NAPRAWA_ALBO_WYMIANA", "Potrzebna naprawa lub wymiana.", "HLAComVoice/Grunt/Choreo/Grunt2/30_0009.wav")
Schema.voices.Add("Combine", "NIE_WIEM", "Nie wiem.", "HLAComVoice/Grunt/Choreo/Grunt2/30_0010.wav")
Schema.voices.Add("Combine", "NIE_WIEM2", "Nie wiem.", "HLAComVoice/Grunt/Choreo/Grunt2/30_0011.wav")
Schema.voices.Add("Combine", "PRZESTAN", "Przestań.", "HLAComVoice/Grunt/Choreo/Grunt2/30_0012.wav")
Schema.voices.Add("Combine", "PRZESTAC_PRACOWAC", "Nadzór mówi, żeby przestać przy tym majstrować.", "HLAComVoice/Grunt/Choreo/Grunt2/30_0013.wav")
Schema.voices.Add("Combine", "ON_PRZESTAL", "On przestał.", "HLAComVoice/Grunt/Choreo/Grunt2/30_0014.wav")
Schema.voices.Add("Combine", "UKRYJ_SIE", "Padnij, ona tu jest!", "HLAComVoice/Grunt/Choreo/Grunt2/30_0015.wav")
Schema.voices.Add("Combine", "CEL_NIEZNANY", "Cel nieznany.", "HLAComVoice/Grunt/Choreo/Grunt2/30_0016.wav")
Schema.voices.Add("Combine", "PRZYJETO2", "Przyjęto.", "HLAComVoice/Grunt/Choreo/Grunt2/30_0020.wav")
Schema.voices.Add("Combine", "TRZYMAJ_JE_W_GORZE2", "Trzymaj je w górze!", "HLAComVoice/Grunt/Choreo/Grunt2/30_0023.wav")
Schema.voices.Add("Combine", "TRZYMAJ_TE_RECE_W_GORZE", "Trzymaj te ręce w górze!", "HLAComVoice/Grunt/Choreo/Grunt2/30_0024.wav")
Schema.voices.Add("Combine", "PODNIES_RECE_W_GORE", "Podnieś ręce w górę!", "HLAComVoice/Grunt/Choreo/Grunt2/30_0025.wav")
Schema.voices.Add("Combine", "PODNIES_TE_RECE_W_GORE", "Podnieś te ręce w górę!", "HLAComVoice/Grunt/Choreo/Grunt2/30_0026.wav")
Schema.voices.Add("Combine", "ONA_JEST_CZYSTA", "Ona nic nie ma.", "HLAComVoice/Grunt/Choreo/Grunt2/30_0027.wav")
Schema.voices.Add("Combine", "RUSZAJ_SIE", "Ruszaj się!", "HLAComVoice/Grunt/Choreo/Grunt2/30_00500.wav")
Schema.voices.Add("Combine", "NAPRZOD4", "Naprzód, naprzód!", "HLAComVoice/Grunt/Choreo/Grunt2/30_00501.wav")
Schema.voices.Add("Combine", "POSUWAJ_SIE3", "Posuwaj się.", "HLAComVoice/Grunt/Choreo/Grunt2/30_00503.wav")
Schema.voices.Add("Combine", "RUSZAM_SIE2", "Ruszam się.", "HLAComVoice/Grunt/Choreo/Grunt2/30_00504.wav")
Schema.voices.Add("Combine", "OCZYSCCIE_ULICE2", "Oczyścić ulice!", "HLAComVoice/Grunt/Choreo/Grunt2/30_00505.wav")
Schema.voices.Add("Combine", "WROC_DO_BLOKU2", "Wróć do swojego bloku mieszkalnego!", "HLAComVoice/Grunt/Choreo/Grunt2/30_00506.wav")
Schema.voices.Add("Combine", "PRZECHODZ", "Przechodź.", "HLAComVoice/Grunt/Choreo/Grunt2/30_00507.wav")
Schema.voices.Add("Combine", "PRZECHODZ4", "Przechodź.", "HLAComVoice/Grunt/Choreo/Grunt2/30_00508.wav")
Schema.voices.Add("Combine", "WSZYSTKO_OK_PRZECHODZ", "Wszystko OK, przechodź.", "HLAComVoice/Grunt/Choreo/Grunt2/30_00509.wav")
Schema.voices.Add("Combine", "WEJDZ", "Wejdź.", "HLAComVoice/Grunt/Choreo/Grunt2/30_00510.wav")
Schema.voices.Add("Combine", "WEJDZ_DO_FURGONU", "Wejdź do furgonu.", "HLAComVoice/Grunt/Choreo/Grunt2/30_00511.wav")
Schema.voices.Add("Combine", "MAMY_ICH2", "Mamy ich!", "HLAComVoice/Grunt/Choreo/Grunt2/30_00517.wav")
Schema.voices.Add("Combine", "POTENCJALNY_ANTYO", "Potencjalny antyobywatel, skanować.", "HLAComVoice/Grunt/Choreo/Grunt2/30_00524.wav")

-- Linie niestandardowe
Schema.voices.Add("Combine", "NIESPOJNOSC", "Niespójność nie będzie tolerowana.", "HLAComVoice/grunt/custom/cognitivedissonance.wav")
Schema.voices.Add("Combine", "OBYWATEL", "Obywatelu.", "HLAComVoice/grunt/custom/citizen.wav")
Schema.voices.Add("Combine", "OBYWATEL2", "Obywatelu.", "HLAComVoice/grunt/custom/citizen2.wav")
Schema.voices.Add("Combine", "OBYWATELE", "Obywatele.", "HLAComVoice/grunt/custom/citizens.wav")
Schema.voices.Add("Combine", "TAK_JEST2", "Tak jest.", "HLAComVoice/grunt/custom/rogerthat2.wav")
Schema.voices.Add("Combine", "TAK_JEST", "Tak jest.", "HLAComVoice/grunt/custom/rogerthat.wav")
Schema.voices.Add("Combine", "10_2_KONIEC", "10-2, koniec.", "HLAComVoice/grunt/custom/102over.wav")
Schema.voices.Add("Combine", "10_2", "10-2.", "HLAComVoice/grunt/custom/102.wav")
Schema.voices.Add("Combine", "10_4", "10-4.", "HLAComVoice/grunt/custom/104.wav")
Schema.voices.Add("Combine", "10_4_KONIEC", "10-4, koniec.", "HLAComVoice/grunt/custom/104over.wav")
Schema.voices.Add("Combine", "PRZYJALEM_KONIEC", "Przyjąłem, koniec.", "HLAComVoice/grunt/custom/copyover.wav")
Schema.voices.Add("Combine", "9_POLSKIE", "Dziewięć.", "HLAComVoice/grunt/custom/nine.wav")
Schema.voices.Add("Combine", "DZIEWIEC2", "Dziewięć.", "HLAComVoice/grunt/custom/nine.wav")

Schema.voices.Add("Combine", "TAK", "Tak.", "HLAComVoice/grunt/custom/yep.wav")
Schema.voices.Add("Combine", "RZUCAM_FLARE", "Rzucam flarę.", "HLAComVoice/grunt/custom/flaredown.wav")
Schema.voices.Add("Combine", "TY", "Ty.", "HLAComVoice/grunt/custom/you.wav")
Schema.voices.Add("Combine", "TY2", "Ty.", "HLAComVoice/grunt/custom/you2.wav")
Schema.voices.Add("Combine", "TY3", "Ty.", "HLAComVoice/grunt/custom/you3.wav")
Schema.voices.Add("Combine", "TY4", "Ty!", "HLAComVoice/grunt/custom/you4.wav")
